import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { DatabaseService } from '../database/database.service.js';
import type { TicketActor } from '../tickets/ticket-actor.service.js';

type ProductStatus = 'DRAFT' | 'ACTIVE' | 'RETIRED';
type AgreementStatus = 'DRAFT' | 'ACTIVE' | 'SUSPENDED' | 'EXPIRED';
type EntitlementStatus = 'ACTIVE' | 'SUSPENDED' | 'EXPIRED';
type PackageStatus = 'DRAFT' | 'ACTIVE' | 'RETIRED';

@Injectable()
export class CommercialService {
  constructor(private readonly database: DatabaseService) {}
  private async platform(userId: string) { const row = (await this.database.query<{ is_platform_admin: boolean }>('SELECT is_platform_admin FROM users WHERE id=$1 AND is_active=true', [userId])).rows[0]; if (!row?.is_platform_admin) throw new ForbiddenException(); }
  private capabilityCode(value: string | undefined) { const code = value?.trim().toUpperCase(); if (!code || !/^[A-Z0-9_.-]{2,120}$/.test(code)) throw new BadRequestException('کد قابلیت معتبر نیست.'); return code; }
  private idempotencyKey(value: string | undefined) { if (!value || !/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)) throw new BadRequestException('کلید تکرارپذیری معتبر نیست.'); return value; }
  private async organizationExists(organizationId: string) { if (!(await this.database.query('SELECT 1 FROM organizations WHERE id=$1', [organizationId])).rowCount) throw new NotFoundException('سازمان یافت نشد.'); }

  async products(userId: string) { await this.platform(userId); return (await this.database.query('SELECT id,code,name,status,created_at,updated_at FROM commercial_products ORDER BY name')).rows; }
  async saveProduct(userId: string, input: { code?: string; name?: string; status?: ProductStatus }) { await this.platform(userId); const code = input.code?.trim().toUpperCase(), name = input.name?.trim(), status = input.status ?? 'DRAFT'; if (!code || !/^[A-Z0-9_-]{2,64}$/.test(code) || !name || name.length < 2 || name.length > 160 || !['DRAFT', 'ACTIVE', 'RETIRED'].includes(status)) throw new BadRequestException('اطلاعات محصول معتبر نیست.'); return this.database.transaction(async client => { const product = (await client.query<{ id: string }>('INSERT INTO commercial_products(code,name,status) VALUES($1,$2,$3) ON CONFLICT(code) DO UPDATE SET name=EXCLUDED.name,status=EXCLUDED.status,updated_at=now() RETURNING id', [code, name, status])).rows[0]; await client.query('INSERT INTO audit_logs(organization_id,actor_user_id,action,target_type,target_id,metadata) VALUES(NULL,$1,$2,$3,$4,$5)', [userId, 'commercial.product_saved', 'commercial_product', product.id, { code, status }]); return product; }); }

  async agreements(userId: string) { await this.platform(userId); return (await this.database.query('SELECT a.id,a.organization_id,o.name AS organization_name,a.agreement_reference,a.status,a.starts_at,a.ends_at FROM organization_commercial_agreements a JOIN organizations o ON o.id=a.organization_id ORDER BY o.name')).rows; }
  async saveAgreement(userId: string, input: { organizationId?: string; agreementReference?: string; status?: AgreementStatus; startsAt?: string; endsAt?: string | null }) { await this.platform(userId); const reference = input.agreementReference?.trim(); if (!input.organizationId || !reference || reference.length > 160 || !input.startsAt || !['DRAFT', 'ACTIVE', 'SUSPENDED', 'EXPIRED'].includes(input.status ?? '')) throw new BadRequestException('اطلاعات قرارداد معتبر نیست.'); return this.database.transaction(async client => { const org = (await client.query<{ id: string }>('SELECT id FROM organizations WHERE id=$1', [input.organizationId])).rows[0]; if (!org) throw new NotFoundException('سازمان یافت نشد.'); const result = (await client.query<{ id: string }>('INSERT INTO organization_commercial_agreements(organization_id,agreement_reference,status,starts_at,ends_at,created_by_user_id) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(organization_id) DO UPDATE SET agreement_reference=EXCLUDED.agreement_reference,status=EXCLUDED.status,starts_at=EXCLUDED.starts_at,ends_at=EXCLUDED.ends_at,updated_at=now() RETURNING id', [org.id, reference, input.status, input.startsAt, input.endsAt ?? null, userId])).rows[0]; await client.query('INSERT INTO audit_logs(organization_id,actor_user_id,action,target_type,target_id,metadata) VALUES($1,$2,$3,$4,$5,$6)', [org.id, userId, 'commercial.agreement_saved', 'commercial_agreement', result.id, { status: input.status }]); return result; }); }

  async entitlements(userId: string) { await this.platform(userId); return (await this.database.query(`SELECT e.id,e.organization_id,o.name AS organization_name,e.product_id,p.name AS product_name,e.capability_code,e.status,e.starts_at,e.ends_at FROM commercial_entitlements e JOIN organizations o ON o.id=e.organization_id LEFT JOIN commercial_products p ON p.id=e.product_id ORDER BY o.name,e.capability_code`)).rows; }
  async saveEntitlement(userId: string, input: { organizationId?: string; productId?: string | null; capabilityCode?: string; status?: EntitlementStatus; startsAt?: string; endsAt?: string | null }) { await this.platform(userId); const capabilityCode = this.capabilityCode(input.capabilityCode), status = input.status ?? 'ACTIVE'; if (!input.organizationId || !input.startsAt || !['ACTIVE', 'SUSPENDED', 'EXPIRED'].includes(status)) throw new BadRequestException('اطلاعات استحقاق معتبر نیست.'); await this.organizationExists(input.organizationId); if (input.productId && !(await this.database.query('SELECT 1 FROM commercial_products WHERE id=$1', [input.productId])).rowCount) throw new NotFoundException('محصول یافت نشد.'); return this.database.withOrganization(input.organizationId, async client => { const record = (await client.query<{ id: string }>('INSERT INTO commercial_entitlements(organization_id,product_id,capability_code,status,starts_at,ends_at) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(organization_id,capability_code) DO UPDATE SET product_id=EXCLUDED.product_id,status=EXCLUDED.status,starts_at=EXCLUDED.starts_at,ends_at=EXCLUDED.ends_at RETURNING id', [input.organizationId, input.productId ?? null, capabilityCode, status, input.startsAt, input.endsAt ?? null])).rows[0]; await client.query('INSERT INTO audit_logs(organization_id,actor_user_id,action,target_type,target_id,metadata) VALUES($1,$2,$3,$4,$5,$6)', [input.organizationId, userId, 'commercial.entitlement_saved', 'commercial_entitlement', record.id, { capabilityCode, status }]); return record; }); }

  async availability(userId: string) { await this.platform(userId); return (await this.database.query('SELECT capability_code,is_available,updated_at FROM platform_capability_availability ORDER BY capability_code')).rows; }
  async saveAvailability(userId: string, input: { capabilityCode?: string; isAvailable?: boolean }) { await this.platform(userId); const code = this.capabilityCode(input.capabilityCode); if (typeof input.isAvailable !== 'boolean') throw new BadRequestException('قابلیت پلتفرم معتبر نیست.'); await this.database.transaction(async client => { await client.query('INSERT INTO platform_capability_availability(capability_code,is_available,updated_by_user_id) VALUES($1,$2,$3) ON CONFLICT(capability_code) DO UPDATE SET is_available=EXCLUDED.is_available,updated_by_user_id=EXCLUDED.updated_by_user_id,updated_at=now()', [code, input.isAvailable, userId]); await client.query('INSERT INTO audit_logs(organization_id,actor_user_id,action,target_type,metadata) VALUES(NULL,$1,$2,$3,$4)', [userId, 'commercial.availability_saved', 'platform_capability', { code, isAvailable: input.isAvailable }]); }); return { capabilityCode: code, isAvailable: input.isAvailable }; }

  async featureSettings(userId: string) { await this.platform(userId); return (await this.database.query('SELECT s.organization_id,o.name AS organization_name,s.capability_code,s.enabled,s.updated_at FROM organization_feature_settings s JOIN organizations o ON o.id=s.organization_id ORDER BY o.name,s.capability_code')).rows; }
  async saveFeatureSetting(userId: string, input: { organizationId?: string; capabilityCode?: string; enabled?: boolean }) { await this.platform(userId); const code = this.capabilityCode(input.capabilityCode); if (!input.organizationId || typeof input.enabled !== 'boolean') throw new BadRequestException('تنظیم قابلیت معتبر نیست.'); await this.organizationExists(input.organizationId); await this.database.withOrganization(input.organizationId, async client => { await client.query('INSERT INTO organization_feature_settings(organization_id,capability_code,enabled,updated_by_user_id) VALUES($1,$2,$3,$4) ON CONFLICT(organization_id,capability_code) DO UPDATE SET enabled=EXCLUDED.enabled,updated_by_user_id=EXCLUDED.updated_by_user_id,updated_at=now()', [input.organizationId, code, input.enabled, userId]); await client.query('INSERT INTO audit_logs(organization_id,actor_user_id,action,target_type,metadata) VALUES($1,$2,$3,$4,$5)', [input.organizationId, userId, 'commercial.feature_setting_saved', 'organization_feature_setting', { code, enabled: input.enabled }]); }); return { organizationId: input.organizationId, capabilityCode: code, enabled: input.enabled }; }

  async addonPackages(userId: string) { await this.platform(userId); return (await this.database.query('SELECT id,code,name,capability_code,unit_count,status,created_at,updated_at FROM commercial_addon_packages ORDER BY name')).rows; }
  async saveAddonPackage(userId: string, input: { code?: string; name?: string; capabilityCode?: string; unitCount?: number; status?: PackageStatus }) { await this.platform(userId); const code = input.code?.trim().toUpperCase(), name = input.name?.trim(), capabilityCode = this.capabilityCode(input.capabilityCode), status = input.status ?? 'DRAFT'; if (!code || !/^[A-Z0-9_-]{2,64}$/.test(code) || !name || name.length < 2 || name.length > 160 || !Number.isInteger(input.unitCount) || (input.unitCount ?? 0) <= 0 || !['DRAFT','ACTIVE','RETIRED'].includes(status)) throw new BadRequestException('اطلاعات بستهٔ افزایشی معتبر نیست.'); return this.database.transaction(async client => { const record = (await client.query<{id:string}>('INSERT INTO commercial_addon_packages(code,name,capability_code,unit_count,status) VALUES($1,$2,$3,$4,$5) ON CONFLICT(code) DO UPDATE SET name=EXCLUDED.name,capability_code=EXCLUDED.capability_code,unit_count=EXCLUDED.unit_count,status=EXCLUDED.status,updated_at=now() RETURNING id',[code,name,capabilityCode,input.unitCount,status])).rows[0]; await client.query('INSERT INTO audit_logs(organization_id,actor_user_id,action,target_type,target_id,metadata) VALUES(NULL,$1,$2,$3,$4,$5)',[userId,'commercial.addon_package_saved','commercial_addon_package',record.id,{code,capabilityCode,unitCount:input.unitCount,status}]); return record; }); }
  async allowances(userId: string) { await this.platform(userId); return (await this.database.query('SELECT a.id,a.organization_id,o.name AS organization_name,a.capability_code,a.period_starts_at,a.period_ends_at,a.granted_units,a.allocation_type,a.created_at FROM commercial_usage_allowances a JOIN organizations o ON o.id=a.organization_id ORDER BY a.created_at DESC')).rows; }
  async addonAllocations(userId: string) { await this.platform(userId); return (await this.database.query('SELECT a.id,a.organization_id,o.name AS organization_name,p.name AS package_name,a.capability_code,a.granted_units,a.created_at FROM commercial_addon_allocations a JOIN organizations o ON o.id=a.organization_id JOIN commercial_addon_packages p ON p.id=a.addon_package_id ORDER BY a.created_at DESC')).rows; }
  async allocateAllowance(userId: string, input: { organizationId?: string; capabilityCode?: string; periodStartsAt?: string; periodEndsAt?: string; grantedUnits?: number; allocationType?: 'PERIODIC'|'EMERGENCY'; idempotencyKey?: string }) { await this.platform(userId); const capabilityCode = this.capabilityCode(input.capabilityCode), key = this.idempotencyKey(input.idempotencyKey), allocationType = input.allocationType ?? 'PERIODIC'; if (!input.organizationId || !input.periodStartsAt || !input.periodEndsAt || !Number.isInteger(input.grantedUnits) || (input.grantedUnits ?? -1) < 0 || !['PERIODIC','EMERGENCY'].includes(allocationType) || new Date(input.periodEndsAt) <= new Date(input.periodStartsAt)) throw new BadRequestException('اطلاعات سهمیه معتبر نیست.'); await this.organizationExists(input.organizationId); return this.database.withOrganization(input.organizationId, async client => { const existing = (await client.query<{id:string}>('SELECT id FROM commercial_usage_allowances WHERE organization_id=$1 AND idempotency_key=$2',[input.organizationId,key])).rows[0]; if (existing) return { id: existing.id, idempotent: true }; const allowance = (await client.query<{id:string}>('INSERT INTO commercial_usage_allowances(organization_id,capability_code,period_starts_at,period_ends_at,granted_units,allocation_type,idempotency_key,created_by_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id',[input.organizationId,capabilityCode,input.periodStartsAt,input.periodEndsAt,input.grantedUnits,allocationType,key,userId])).rows[0]; await client.query('INSERT INTO commercial_usage_ledger(organization_id,capability_code,unit_count,event_type,idempotency_key,metadata) VALUES($1,$2,$3,$4,$5,$6)',[input.organizationId,capabilityCode,input.grantedUnits,'ALLOWANCE_ALLOCATED',key,{allowanceId:allowance.id,allocationType}]); await client.query('INSERT INTO audit_logs(organization_id,actor_user_id,action,target_type,target_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[input.organizationId,userId,'commercial.allowance_allocated','commercial_usage_allowance',allowance.id,{capabilityCode,grantedUnits:input.grantedUnits,allocationType}]); return { id: allowance.id, idempotent: false }; }); }
  async allocateAddon(userId: string, input: { organizationId?: string; addonPackageId?: string; grantedUnits?: number; idempotencyKey?: string }) { await this.platform(userId); const key = this.idempotencyKey(input.idempotencyKey); if (!input.organizationId || !input.addonPackageId || !Number.isInteger(input.grantedUnits) || (input.grantedUnits ?? 0) <= 0) throw new BadRequestException('اطلاعات تخصیص بسته معتبر نیست.'); await this.organizationExists(input.organizationId); const pack = (await this.database.query<{id:string;capability_code:string;status:string}>('SELECT id,capability_code,status FROM commercial_addon_packages WHERE id=$1',[input.addonPackageId])).rows[0]; if (!pack || pack.status !== 'ACTIVE') throw new BadRequestException('بستهٔ افزایشی فعال یافت نشد.'); return this.database.withOrganization(input.organizationId, async client => { const existing = (await client.query<{id:string}>('SELECT id FROM commercial_addon_allocations WHERE organization_id=$1 AND idempotency_key=$2',[input.organizationId,key])).rows[0]; if (existing) return { id: existing.id, idempotent: true }; const allocation = (await client.query<{id:string}>('INSERT INTO commercial_addon_allocations(organization_id,addon_package_id,capability_code,granted_units,idempotency_key,created_by_user_id) VALUES($1,$2,$3,$4,$5,$6) RETURNING id',[input.organizationId,pack.id,pack.capability_code,input.grantedUnits,key,userId])).rows[0]; await client.query('INSERT INTO commercial_usage_ledger(organization_id,capability_code,unit_count,event_type,idempotency_key,metadata) VALUES($1,$2,$3,$4,$5,$6)',[input.organizationId,pack.capability_code,input.grantedUnits,'ADDON_ALLOCATED',key,{addonAllocationId:allocation.id,addonPackageId:pack.id}]); await client.query('INSERT INTO audit_logs(organization_id,actor_user_id,action,target_type,target_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[input.organizationId,userId,'commercial.addon_allocated','commercial_addon_allocation',allocation.id,{capabilityCode:pack.capability_code,grantedUnits:input.grantedUnits}]); return { id: allocation.id, idempotent: false }; }); }
  async commercialState(actor: TicketActor) { return this.database.withOrganization(actor.organizationId, async client => ({ allowances: (await client.query('SELECT capability_code,period_starts_at,period_ends_at,granted_units,allocation_type FROM commercial_usage_allowances WHERE period_ends_at>now() ORDER BY period_ends_at')).rows, addons: (await client.query('SELECT capability_code,granted_units,created_at FROM commercial_addon_allocations ORDER BY created_at DESC')).rows, ledger: (await client.query('SELECT capability_code,unit_count,event_type,occurred_at FROM commercial_usage_ledger ORDER BY occurred_at DESC LIMIT 50')).rows })); }
  async ownerDashboard(actor: TicketActor) { if(!actor.roles.includes('ORG_OWNER')) throw new ForbiddenException('فقط مالک سازمان به این نمای تجاری دسترسی دارد.'); return this.database.withOrganization(actor.organizationId,async client=>({ allowances:(await client.query("SELECT capability_code,allocation_type,granted_units,period_ends_at FROM commercial_usage_allowances WHERE period_ends_at>now() ORDER BY period_ends_at")).rows, addons:(await client.query('SELECT capability_code,granted_units,created_at FROM commercial_addon_allocations ORDER BY created_at DESC')).rows, ai:(await client.query("SELECT count(*)::int AS request_count,COALESCE(sum(COALESCE((usage->>'inputTokens')::int,0)+COALESCE((usage->>'outputTokens')::int,0)),0)::int AS token_count FROM ai_results")).rows[0], assist:(await client.query("SELECT p.capacity_units,p.request_policy,p.default_access_scope,p.assist_sla_minutes,count(c.id) FILTER(WHERE c.status IN ('QUEUED','ACCEPTED','IN_PROGRESS','WAITING_FOR_ORGANIZATION'))::int AS active_cases FROM organization_assist_policies p LEFT JOIN assist_cases c ON c.organization_id=p.organization_id WHERE p.organization_id=$1 GROUP BY p.capacity_units,p.request_policy,p.default_access_scope,p.assist_sla_minutes",[actor.organizationId])).rows[0]??null })); }

  async reserveSmartAction(actor: TicketActor, capabilityCode: string, idempotencyKey: string) { const capability = this.capabilityCode(capabilityCode), key = this.idempotencyKey(idempotencyKey); await this.requireEffective(actor, capability); return this.database.withOrganization(actor.organizationId, async client => { await client.query('SELECT pg_advisory_xact_lock(hashtext($1))',[`${actor.organizationId}:${capability}`]); const existing=(await client.query<{id:string;status:string;reservation_source:string}>('SELECT id,status,reservation_source FROM commercial_smart_actions WHERE organization_id=$1 AND idempotency_key=$2',[actor.organizationId,key])).rows[0]; if(existing)return {...existing,idempotent:true}; const used=async(source:string)=>Number((await client.query<{units:string}>('SELECT COALESCE(sum(unit_count),0)::text AS units FROM commercial_smart_actions WHERE capability_code=$1 AND reservation_source=$2 AND status IN (\'RESERVED\',\'SETTLED\')',[capability,source])).rows[0]?.units??0); const periodic=Number((await client.query<{units:string}>("SELECT COALESCE(sum(granted_units),0)::text AS units FROM commercial_usage_allowances WHERE capability_code=$1 AND allocation_type='PERIODIC' AND period_starts_at<=now() AND period_ends_at>now()",[capability])).rows[0]?.units??0); const addons=Number((await client.query<{units:string}>('SELECT COALESCE(sum(granted_units),0)::text AS units FROM commercial_addon_allocations WHERE capability_code=$1',[capability])).rows[0]?.units??0); const emergency=Number((await client.query<{units:string}>("SELECT COALESCE(sum(granted_units),0)::text AS units FROM commercial_usage_allowances WHERE capability_code=$1 AND allocation_type='EMERGENCY' AND period_starts_at<=now() AND period_ends_at>now()",[capability])).rows[0]?.units??0); const source=(periodic-await used('PERIODIC')>=1?'PERIODIC':addons-await used('ADDON')>=1?'ADDON':emergency-await used('EMERGENCY')>=1?'EMERGENCY':null); if(!source)throw new ForbiddenException('سهمیهٔ Smart Action برای سازمان شما کافی نیست.'); const action=(await client.query<{id:string}>('INSERT INTO commercial_smart_actions(organization_id,capability_code,idempotency_key,reservation_source,status) VALUES($1,$2,$3,$4,\'RESERVED\') RETURNING id',[actor.organizationId,capability,key,source])).rows[0]; return {...action,status:'RESERVED',reservation_source:source,idempotent:false}; }); }
  async settleSmartAction(organizationId: string, idempotencyKey: string, deliveryReference: string) { const key=this.idempotencyKey(idempotencyKey); return this.database.withOrganization(organizationId,async client=>{const action=(await client.query<{id:string;capability_code:string;unit_count:number;status:string;reservation_source:string}>('SELECT id,capability_code,unit_count,status,reservation_source FROM commercial_smart_actions WHERE organization_id=$1 AND idempotency_key=$2 FOR UPDATE',[organizationId,key])).rows[0];if(!action)throw new NotFoundException('Smart Action یافت نشد.');if(action.status==='SETTLED')return{id:action.id,idempotent:true};if(action.status!=='RESERVED')throw new BadRequestException('Smart Action قابل تسویه نیست.');await client.query('INSERT INTO commercial_usage_ledger(organization_id,capability_code,unit_count,event_type,idempotency_key,metadata) VALUES($1,$2,$3,$4,$5,$6)',[organizationId,action.capability_code,-action.unit_count,'SMART_ACTION_SETTLED',key,{smartActionId:action.id,deliveryReference}]);await client.query("UPDATE commercial_smart_actions SET status='SETTLED',delivery_reference=$2,settled_at=now() WHERE id=$1",[action.id,deliveryReference]);await client.query('INSERT INTO audit_logs(organization_id,actor_user_id,action,target_type,target_id,metadata) VALUES($1,NULL,$2,$3,$4,$5)',[organizationId,'commercial.smart_action_settled','commercial_smart_action',action.id,{capabilityCode:action.capability_code,reservationSource:action.reservation_source,deliveryReference}]);return{id:action.id,idempotent:false};}); }
  async releaseSmartAction(organizationId: string, idempotencyKey: string) { const key=this.idempotencyKey(idempotencyKey); return this.database.withOrganization(organizationId,async client=>{const result=await client.query("UPDATE commercial_smart_actions SET status='RELEASED',released_at=now() WHERE organization_id=$1 AND idempotency_key=$2 AND status='RESERVED' RETURNING id",[organizationId,key]);if(result.rowCount)await client.query('INSERT INTO audit_logs(organization_id,actor_user_id,action,target_type,target_id,metadata) VALUES($1,NULL,$2,$3,$4,$5)',[organizationId,'commercial.smart_action_released','commercial_smart_action',result.rows[0].id,{}]);return{released:Boolean(result.rowCount)};}); }

  async resolve(organizationId: string, rawCapabilityCode: string) { const capabilityCode = this.capabilityCode(rawCapabilityCode); const available = Boolean((await this.database.query<{ is_available: boolean }>('SELECT is_available FROM platform_capability_availability WHERE capability_code=$1', [capabilityCode])).rows[0]?.is_available); const tenant = await this.database.withOrganization(organizationId, async client => { const entitlement = Boolean((await client.query<{ allowed: boolean }>(`SELECT EXISTS(SELECT 1 FROM commercial_entitlements WHERE capability_code=$1 AND status='ACTIVE' AND starts_at<=now() AND (ends_at IS NULL OR ends_at>now())) AS allowed`, [capabilityCode])).rows[0]?.allowed); const setting = Boolean((await client.query<{ enabled: boolean }>('SELECT enabled FROM organization_feature_settings WHERE capability_code=$1', [capabilityCode])).rows[0]?.enabled); return { entitlement, setting }; }); return { organizationId, capabilityCode, effective: available && tenant.entitlement && tenant.setting, checks: { entitlement: tenant.entitlement, organizationSetting: tenant.setting, platformAvailability: available } }; }
  async effectiveCapabilities(actor: TicketActor) { const codes = new Set<string>(); (await this.database.query<{ capability_code: string }>('SELECT capability_code FROM platform_capability_availability')).rows.forEach(row => codes.add(row.capability_code)); await this.database.withOrganization(actor.organizationId, async client => { (await client.query<{ capability_code: string }>('SELECT capability_code FROM commercial_entitlements UNION SELECT capability_code FROM organization_feature_settings')).rows.forEach(row => codes.add(row.capability_code)); }); return Promise.all([...codes].sort().map(code => this.resolve(actor.organizationId, code))); }
  async requireEffective(actor: TicketActor, capabilityCode: string) { const result = await this.resolve(actor.organizationId, capabilityCode); if (!result.effective) throw new ForbiddenException('این قابلیت برای سازمان شما فعال نیست.'); return result; }
}
