-- GOAL-038: intentionally minimal commercial records. Capability resolution
-- and allowance settlement are introduced only in later Goals.
CREATE TABLE commercial_products (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code text NOT NULL UNIQUE CHECK (code ~ '^[A-Z0-9_-]{2,64}$'), name text NOT NULL CHECK (char_length(name) BETWEEN 2 AND 160), status text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('DRAFT','ACTIVE','RETIRED')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE commercial_subscriptions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT, product_id uuid NOT NULL REFERENCES commercial_products(id) ON DELETE RESTRICT, status text NOT NULL CHECK (status IN ('ACTIVE','SUSPENDED','EXPIRED','CANCELLED')), starts_at timestamptz NOT NULL, ends_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), CHECK (ends_at IS NULL OR ends_at>starts_at)
);
CREATE TABLE commercial_entitlements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, product_id uuid REFERENCES commercial_products(id) ON DELETE SET NULL, capability_code text NOT NULL CHECK (capability_code ~ '^[A-Z0-9_.-]{2,120}$'), status text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','SUSPENDED','EXPIRED')), starts_at timestamptz NOT NULL DEFAULT now(), ends_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), CHECK (ends_at IS NULL OR ends_at>starts_at), UNIQUE(organization_id,capability_code)
);
CREATE TABLE commercial_addon_packages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code text NOT NULL UNIQUE, name text NOT NULL, status text NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('DRAFT','ACTIVE','RETIRED')), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE organization_commercial_agreements (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL UNIQUE REFERENCES organizations(id) ON DELETE CASCADE, agreement_reference text NOT NULL, status text NOT NULL CHECK(status IN ('DRAFT','ACTIVE','SUSPENDED','EXPIRED')), starts_at timestamptz NOT NULL, ends_at timestamptz, created_by_user_id uuid NOT NULL REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK(ends_at IS NULL OR ends_at>starts_at));
CREATE TABLE platform_capability_availability (capability_code text PRIMARY KEY, is_available boolean NOT NULL DEFAULT true, updated_by_user_id uuid REFERENCES users(id), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE organization_feature_settings (organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, capability_code text NOT NULL, enabled boolean NOT NULL DEFAULT false, updated_by_user_id uuid REFERENCES users(id), updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(organization_id,capability_code));
CREATE TABLE commercial_usage_allowances (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, capability_code text NOT NULL, period_starts_at timestamptz NOT NULL, period_ends_at timestamptz NOT NULL, granted_units integer NOT NULL CHECK(granted_units>=0), created_at timestamptz NOT NULL DEFAULT now(), CHECK(period_ends_at>period_starts_at));
CREATE TABLE commercial_usage_ledger (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, capability_code text NOT NULL, unit_count integer NOT NULL CHECK(unit_count<>0), event_type text NOT NULL, occurred_at timestamptz NOT NULL DEFAULT now(), idempotency_key uuid, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, UNIQUE(organization_id,idempotency_key));
ALTER TABLE commercial_subscriptions ENABLE ROW LEVEL SECURITY; ALTER TABLE commercial_entitlements ENABLE ROW LEVEL SECURITY; ALTER TABLE organization_commercial_agreements ENABLE ROW LEVEL SECURITY; ALTER TABLE organization_feature_settings ENABLE ROW LEVEL SECURITY; ALTER TABLE commercial_usage_allowances ENABLE ROW LEVEL SECURITY; ALTER TABLE commercial_usage_ledger ENABLE ROW LEVEL SECURITY;
CREATE POLICY commercial_subscriptions_tenant ON commercial_subscriptions USING(organization_id=app.current_organization_id()) WITH CHECK(organization_id=app.current_organization_id());
CREATE POLICY commercial_entitlements_tenant ON commercial_entitlements USING(organization_id=app.current_organization_id()) WITH CHECK(organization_id=app.current_organization_id());
CREATE POLICY organization_commercial_agreements_tenant ON organization_commercial_agreements USING(organization_id=app.current_organization_id()) WITH CHECK(organization_id=app.current_organization_id());
CREATE POLICY organization_feature_settings_tenant ON organization_feature_settings USING(organization_id=app.current_organization_id()) WITH CHECK(organization_id=app.current_organization_id());
CREATE POLICY commercial_usage_allowances_tenant ON commercial_usage_allowances USING(organization_id=app.current_organization_id()) WITH CHECK(organization_id=app.current_organization_id());
CREATE POLICY commercial_usage_ledger_tenant ON commercial_usage_ledger USING(organization_id=app.current_organization_id()) WITH CHECK(organization_id=app.current_organization_id());
GRANT SELECT,INSERT,UPDATE,DELETE ON commercial_products,commercial_subscriptions,commercial_entitlements,commercial_addon_packages,organization_commercial_agreements,platform_capability_availability,organization_feature_settings,commercial_usage_allowances,commercial_usage_ledger TO jupiter_app;
