import { useEffect, useState } from 'react';
import { NavLink } from 'react-router-dom';
import type { Actor } from './App';
import { request } from './App';

type Overview = { total:number;active:number;in_progress:number;waiting:number;completed:number;unassigned:number;at_risk:number;recent:Array<{id:string;ticket_number:number;title:string;status:string;priority:string;updated_at:string;assignee_display_name?:string}> };
const labels: Record<string,string> = { OPEN:'باز',IN_PROGRESS:'در حال رسیدگی',WAITING_FOR_REQUESTER:'منتظر پاسخ',RESOLVED:'حل‌شده',CLOSED:'بسته' };

export function DashboardPro({ actor, staff }: { actor: Actor; staff: boolean }) {
  const [data,setData]=useState<Overview|null>(null); const [error,setError]=useState('');
  useEffect(()=>{request('/dashboard/overview',actor.session,actor.organizationId).then(setData).catch((cause)=>setError(cause.message));},[actor.organizationId]);
  const cards=data?[['کارهای فعال',data.active,'/tickets'],[staff?'در حال رسیدگی':'در انتظار پاسخ',staff?data.in_progress:data.waiting,'/tickets'],[staff?'ریسک SLA':'حل یا بسته‌شده',staff?data.at_risk:data.completed,'/tickets'],[staff?'بدون مسئول':'همه درخواست‌ها',staff?data.unassigned:data.total,'/tickets']]:[];
  return <section className="page dashboard-pro"><div className="page-intro"><div><p className="eyebrow">نمای عملیاتی امروز</p><h2>{staff?'صف کار و اولویت‌های تیم':'درخواست‌های شما'}</h2><p>{staff?'شاخص‌ها بر مبنای وضعیت لحظه‌ای سازمان هستند.':'آخرین وضعیت درخواست‌ها و پاسخ‌های مورد نیاز را از اینجا پیگیری کنید.'}</p></div><NavLink className="button-link" to="/tickets">{staff?'باز کردن صف کاری':'ثبت درخواست جدید'}</NavLink></div>{error&&<p className="error" role="alert">{error}</p>}{!data?<p className="hint">در حال آماده‌سازی نمای عملیاتی…</p>:<><div className="metric-grid actionable-metrics">{cards.map(([label,value,to])=><NavLink className="metric-card" key={String(label)} to={String(to)}><span>{label}</span><strong>{value}</strong><small>مشاهده تیکت‌های مرتبط ←</small></NavLink>)}</div>{staff&&data.at_risk>0&&<section className="risk-banner"><div><strong>{data.at_risk} تیکت در آستانه سررسید SLA است</strong><p>اولویت‌بندی و تخصیص این موارد را بررسی کنید.</p></div><NavLink to="/tickets" className="button-link">مشاهده ریسک‌ها</NavLink></section>}<section className="card recent-work"><div className="section-heading"><div><h3>آخرین فعالیت‌ها</h3><p className="hint">تا ۸ تیکت به‌روز شده اخیر</p></div><NavLink to="/tickets">همه تیکت‌ها</NavLink></div><div className="table-wrap"><table><thead><tr><th>شماره</th><th>عنوان</th><th>وضعیت</th><th>مسئول</th><th>به‌روزرسانی</th></tr></thead><tbody>{data.recent.map((ticket)=><tr key={ticket.id}><td>#{ticket.ticket_number}</td><td>{ticket.title}</td><td>{labels[ticket.status]??ticket.status}</td><td>{ticket.assignee_display_name??'بدون مسئول'}</td><td>{new Date(ticket.updated_at).toLocaleString('fa-IR')}</td></tr>)}{!data.recent.length&&<tr><td colSpan={5}>فعالیتی ثبت نشده است.</td></tr>}</tbody></table></div></section></>}</section>;
}
