import { FormEvent, useEffect, useMemo, useState } from 'react';
import type { Actor } from './App';
import { request } from './App';

type Article = { id:string; title:string; body:string; status:string; updated_at:string; published_at?:string; author_display_name?:string; reviewer_display_name?:string };
const labels: Record<string,string> = { DRAFT:'پیش‌نویس', IN_REVIEW:'در انتظار بازبینی', PUBLISHED:'منتشرشده', ARCHIVED:'بایگانی‌شده' };

export function KnowledgeWorkspacePro({ actor }: { actor: Actor }) {
  const staff=actor.membership.role_codes.some((role) => ['ORG_ADMIN','SUPERVISOR','EXPERT'].includes(role)); const reviewer=actor.membership.role_codes.some((role) => ['ORG_ADMIN','SUPERVISOR'].includes(role));
  const [search,setSearch]=useState(''); const [published,setPublished]=useState<Article[]>([]); const [workspace,setWorkspace]=useState<Article[]>([]); const [selected,setSelected]=useState<Article|null>(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
  const load = () => { setLoading(true); const calls=[request(`/knowledge?q=${encodeURIComponent(search)}`,actor.session,actor.organizationId)]; if(staff) calls.push(request('/knowledge/workspace',actor.session,actor.organizationId)); Promise.all(calls).then(([articles,drafts]) => {setPublished(articles as Article[]);setWorkspace((drafts ?? []) as Article[]);}).catch((cause)=>setError(cause.message)).finally(()=>setLoading(false));};
  useEffect(()=>{void load();},[actor.organizationId]);
  const selectable=useMemo(()=>selected ?? published[0] ?? workspace[0] ?? null,[selected,published,workspace]);
  return <section className="knowledge-pro page"><div className="page-intro"><div><p className="eyebrow">دانش‌نامه سازمانی</p><h2>پاسخ‌های قابل اعتماد، در دسترس همه</h2><p>مقاله‌ها پس از بازبینی منتشر می‌شوند و تاریخچه و مالکیت آن‌ها قابل پیگیری است.</p></div>{staff && <button type="button" onClick={()=>setSelected({id:'new',title:'',body:'',status:'DRAFT',updated_at:''})}>پیشنهاد مقاله</button>}</div>{error && <p className="error" role="alert">{error}</p>}<div className="knowledge-layout"><aside className="knowledge-list"><div className="knowledge-search"><input value={search} onChange={(event)=>setSearch(event.target.value)} onKeyDown={(event)=>{if(event.key==='Enter')load();}} placeholder="جست‌وجو در مقاله‌های منتشرشده"/><button className="secondary" type="button" onClick={load}>جست‌وجو</button></div><section><h3>منتشرشده</h3>{loading&&<p className="hint">در حال جست‌وجو…</p>}{published.map((article)=><ArticleButton key={article.id} article={article} selected={selectable?.id===article.id} onClick={()=>setSelected(article)}/>) }{!published.length&&!loading&&<p className="hint">مقاله‌ای پیدا نشد.</p>}</section>{staff&&<section><h3>فضای نویسندگی</h3>{workspace.map((article)=><ArticleButton key={article.id} article={article} selected={selectable?.id===article.id} onClick={()=>setSelected(article)}/>) }{!workspace.length&&<p className="hint">پیش‌نویس یا مقاله قابل بازبینی وجود ندارد.</p>}</section>}</aside><main className="knowledge-detail">{selectable ? <ArticleEditor actor={actor} article={selectable} canReview={reviewer} onSaved={(article)=>{setSelected(article);load();}}/> : <div className="empty-state"><h3>یک مقاله انتخاب کنید</h3><p>برای مشاهده یا ویرایش، مقاله‌ای را از فهرست انتخاب کنید.</p></div>}</main></div></section>;
}

function ArticleButton({article,selected,onClick}:{article:Article;selected:boolean;onClick:()=>void}) { return <button type="button" className={`article-button ${selected?'selected':''}`} onClick={onClick}><strong>{article.title}</strong><span><span className={`status-pill knowledge-${article.status.toLowerCase()}`}>{labels[article.status]??article.status}</span>{article.author_display_name&&` · ${article.author_display_name}`}</span></button>; }

function ArticleEditor({ actor, article, canReview, onSaved }: { actor:Actor;article:Article;canReview:boolean;onSaved:(article:Article)=>void }) {
  const editable=article.status !== 'PUBLISHED' || canReview; const [title,setTitle]=useState(article.title); const [body,setBody]=useState(article.body); const [revisions,setRevisions]=useState<{version:number;created_at:string}[]>([]); const [notice,setNotice]=useState(''); const [error,setError]=useState('');
  useEffect(()=>{setTitle(article.title);setBody(article.body);setNotice('');setError(''); if(article.id!=='new') request(`/knowledge/${article.id}/revisions`,actor.session,actor.organizationId).then(setRevisions).catch(()=>setRevisions([]));},[article.id]);
  const save=async(event:FormEvent)=>{event.preventDefault();try{const next=article.id==='new'?await request('/knowledge',actor.session,actor.organizationId,{method:'POST',body:JSON.stringify({title,body})}):await request(`/knowledge/${article.id}`,actor.session,actor.organizationId,{method:'POST',body:JSON.stringify({title,body})});onSaved({...article,...next,title,body});setNotice('پیش‌نویس ذخیره شد.');}catch(cause){setError(cause instanceof Error?cause.message:'ذخیره ناموفق بود.');}};
  const action=async(path:string,message:string)=>{try{const next=await request(path,actor.session,actor.organizationId,{method:'POST'});onSaved({...article,...next,title,body});setNotice(message);}catch(cause){setError(cause instanceof Error?cause.message:'عملیات ناموفق بود.');}};
  if(!editable) return <article className="article-reader"><p className="eyebrow">{labels[article.status]}</p><h2>{article.title}</h2><p className="article-meta">نویسنده: {article.author_display_name ?? '—'} · {article.published_at ? new Date(article.published_at).toLocaleDateString('fa-IR') : ''}</p><div className="article-body">{article.body}</div></article>;
  return <article className="article-editor"><div className="editor-heading"><div><p className="eyebrow">{labels[article.status] ?? 'مقاله جدید'}</p><h2>{article.id==='new'?'پیشنهاد مقاله':article.title}</h2></div>{article.id!=='new'&&<span className="hint">{revisions.length} نسخه ثبت‌شده</span>}</div><form onSubmit={save}><label>عنوان<input value={title} minLength={3} maxLength={200} onChange={(event)=>setTitle(event.target.value)} required/></label><label>متن مقاله<textarea className="article-textarea" value={body} maxLength={20000} onChange={(event)=>setBody(event.target.value)} required/></label>{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}<div className="inline-actions"><button>ذخیره پیش‌نویس</button>{article.id!=='new'&&article.status==='DRAFT'&&<button type="button" className="secondary" onClick={()=>action(`/knowledge/${article.id}/submit-review`,'برای بازبینی ارسال شد.')}>ارسال برای بازبینی</button>}{article.id!=='new'&&article.status==='IN_REVIEW'&&canReview&&<button type="button" onClick={()=>action(`/knowledge/${article.id}/publish`,'مقاله منتشر شد.')}>انتشار</button>}{article.id!=='new'&&canReview&&article.status!=='ARCHIVED'&&<button type="button" className="secondary" onClick={()=>action(`/knowledge/${article.id}/archive`,'مقاله بایگانی شد.')}>بایگانی</button>}</div></form>{revisions.length>0&&<details className="revision-history"><summary>تاریخچه نسخه‌ها</summary>{revisions.map((revision)=><p key={revision.version}>نسخه {revision.version} · {new Date(revision.created_at).toLocaleString('fa-IR')}</p>)}</details>}</article>;
}
