import { FormEvent, type ReactNode, useEffect, useState } from 'react';
import type { Actor } from './App'; import { request } from './App'; import { ContextualHelpTrigger } from './ContextualHelp';
type Usage={capability_code:string;periodic:number;addon:number;emergency:number;periodicUsed:number;addonUsed:number;emergencyUsed:number;overage:{enabled:boolean;limit_units:number};overageUsed:number};
type Dashboard={subscriptions:{id:string;product_name:string;status:string;ends_at:string|null;grace_ends_at:string|null;days_remaining:number|null}[];overage:Usage[];requests:{id:string;request_type:string;status:string;decision_note:string|null}[];assist:null|{capacity_units:number;active_cases:number};warnings?:string[]};
type SmartActionSummary={capability_code:string;consumed_units:number;reserved_units:number;periodic_units:number;addon_units:number;emergency_units:number;overage_units:number};
const subscriptionStatus:Record<string,string>={TRIAL:'آزمایشی',ACTIVE:'فعال',PAST_DUE:'دارای بدهی',SUSPENDED:'تعلیق‌شده',CANCELLED:'لغوشده',EXPIRED:'منقضی'};
const n=(x:number)=>Number(x??0).toLocaleString('fa-IR'); const d=(x:string|null)=>x?new Date(x).toLocaleDateString('fa-IR'):'—';
export function OwnerCommercialDashboard({actor}:{actor:Actor}) {
  const [data,setData]=useState<Dashboard|null>(null),[actions,setActions]=useState<SmartActionSummary[]>([]),[error,setError]=useState(''),[policy,setPolicy]=useState({capabilityCode:'',enabled:false,limitUnits:10}),[form,setForm]=useState({requestType:'ADDON',capabilityCode:'',requestedUnits:10,subscriptionId:'',requestNote:''});
  const load=()=>Promise.all([request('/platform/commercial/owner-dashboard',actor.session,actor.organizationId),request('/platform/commercial/owner/smart-actions',actor.session,actor.organizationId)]).then(([dashboard,summary])=>{setData(dashboard as Dashboard);setActions(summary as SmartActionSummary[]);}).catch(e=>setError(e instanceof Error?e.message:'دریافت نمای تجاری ناموفق بود.'));
  useEffect(()=>{void load();},[actor.organizationId,actor.session]);
  const send=async(e:FormEvent,path:string,body:unknown)=>{e.preventDefault();try{await request(path,actor.session,actor.organizationId,{method:'POST',headers:path.endsWith('requests')?{'idempotency-key':crypto.randomUUID()}:undefined,body:JSON.stringify(body)});await load();}catch(x){setError(x instanceof Error?x.message:'ثبت اطلاعات ناموفق بود.');}};
  if(error)return <p className="error" role="alert">{error}</p>; if(!data)return <p className="hint">در حال دریافت اطلاعات…</p>;
  return <div className="admin-stack owner-commercial-dashboard">
    <section className="card"><div className="contextual-help-row"><div><h3>سهمیه و پشتیبانی</h3><p className="hint">ثبت دستی تیکت مستقل از سهمیهٔ اقدامات هوشمند است.</p></div><ContextualHelpTrigger actor={actor} relatedFeature="COMMERCIAL_DASHBOARD" label="راهنمای سهمیه و مصرف مازاد"/></div>{data.warnings?.length?<div className="notice warning">{data.warnings.map(x=><p key={x}>{x}</p>)}</div>:null}<h4>سرویس‌ها و اشتراک‌ها</h4><Table heads={['سرویس','وضعیت','پایان / مهلت','باقی‌مانده']} rows={data.subscriptions.map(x=>[x.product_name,subscriptionStatus[x.status]??x.status,x.status==='PAST_DUE'?d(x.grace_ends_at):d(x.ends_at),x.days_remaining===null?'—':`${n(x.days_remaining)} روز`])} empty="اشتراکی ثبت نشده است."/><p className="hint">تیکت‌گذاری دستی همیشه برقرار است، حتی وقتی دستیار هوشمند در دسترس نیست.</p></section>
    <section className="card"><h3>مصرف اقدامات هوشمند</h3><Table heads={['قابلیت','مصرف‌شده','در انتظار','منبع مصرف']} rows={actions.map(x=>[<span dir="ltr">{x.capability_code}</span>,n(x.consumed_units),n(x.reserved_units),`دوره‌ای ${n(x.periodic_units)} · بسته ${n(x.addon_units)} · اضطراری ${n(x.emergency_units)} · مازاد ${n(x.overage_units)}`])} empty="مصرفی ثبت نشده است."/><p className="hint">هر تحلیل کامل Intake یک اقدام است؛ تلاش مجدد، خطا و تبدیل صوتِ مستقل مصرف جداگانه ندارند.</p></section>
    <section className="card"><h3>ظرفیت و ترتیب مصرف</h3><p className="hint">دوره‌ای ← بسته افزایشی ← اضطراری ← مصرف مازاد ← توقف Smart Action</p><Table heads={['قابلیت','دوره‌ای / باقی‌مانده','بسته / باقی‌مانده','اضطراری / باقی‌مانده','مصرف مازاد']} rows={data.overage.map(x=>[<span dir="ltr">{x.capability_code}</span>,`${n(x.periodic)} / ${n(x.periodic-x.periodicUsed)}`,`${n(x.addon)} / ${n(x.addon-x.addonUsed)}`,`${n(x.emergency)} / ${n(x.emergency-x.emergencyUsed)}`,`${x.overage.enabled?'فعال':'غیرفعال'} · سقف ${n(x.overage.limit_units)} · مصرف ${n(x.overageUsed)}`])} empty="ظرفیتی ثبت نشده است."/><p className="hint">ظرفیت Assist: {n(data.assist?.capacity_units??0)} · پرونده‌های فعال: {n(data.assist?.active_cases??0)}</p><form className="compact-form" onSubmit={e=>void send(e,'/platform/commercial/owner/overage',policy)}><label>قابلیت<input dir="ltr" required value={policy.capabilityCode} onChange={e=>setPolicy({...policy,capabilityCode:e.target.value.toUpperCase()})}/></label><label>وضعیت<select value={String(policy.enabled)} onChange={e=>setPolicy({...policy,enabled:e.target.value==='true'})}><option value="false">غیرفعال</option><option value="true">فعال</option></select></label><label>سقف<input type="number" min={policy.enabled?1:0} value={policy.limitUnits} onChange={e=>setPolicy({...policy,limitUnits:Number(e.target.value)})}/></label><button>ذخیرهٔ مصرف مازاد</button></form></section>
    <section className="card"><h3>درخواست تجاری</h3><form className="compact-form" onSubmit={e=>void send(e,'/platform/commercial/owner/requests',form)}><label>نوع<select value={form.requestType} onChange={e=>setForm({...form,requestType:e.target.value})}><option value="ADDON">بسته افزایشی</option><option value="RENEWAL">تمدید</option><option value="SERVICE_ACTIVATION">فعال‌سازی سرویس</option></select></label>{form.requestType!=='RENEWAL'&&<label>قابلیت<input dir="ltr" required value={form.capabilityCode} onChange={e=>setForm({...form,capabilityCode:e.target.value.toUpperCase()})}/></label>}{form.requestType==='ADDON'&&<label>واحد<input type="number" min="1" value={form.requestedUnits} onChange={e=>setForm({...form,requestedUnits:Number(e.target.value)})}/></label>}{form.requestType==='RENEWAL'&&<label>اشتراک<select required value={form.subscriptionId} onChange={e=>setForm({...form,subscriptionId:e.target.value})}><option value="">انتخاب کنید</option>{data.subscriptions.map(x=><option key={x.id} value={x.id}>{x.product_name}</option>)}</select></label>}<button>ارسال درخواست</button></form><Table heads={['نوع','وضعیت','نتیجه']} rows={data.requests.map(x=>[x.request_type,x.status,x.decision_note??'—'])} empty="درخواستی ثبت نشده است."/></section>
  </div>;
}
function Table({heads,rows,empty}:{heads:string[];rows:ReactNode[][];empty:string}){return <div className="table-wrap"><table><thead><tr>{heads.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>):<tr><td colSpan={heads.length}>{empty}</td></tr>}</tbody></table></div>}
