import { FormEvent, type ReactNode, useEffect, useState } from 'react';
import type { Actor } from './App'; import { request } from './App'; import { ContextualHelpTrigger } from './ContextualHelp';
type Usage={capability_code:string;periodic:number;addon:number;emergency:number;periodicUsed:number;addonUsed:number;emergencyUsed:number;overage:{enabled:boolean;limit_units:number};overageUsed:number};
type Dashboard={subscriptions:{id:string;product_name:string;status:string;ends_at:string|null;grace_ends_at:string|null;days_remaining:number|null}[];overage:Usage[];requests:{id:string;request_type:string;status:string;decision_note:string|null}[];assist:null|{capacity_units:number;active_cases:number};warnings?:string[]};
type SmartActionSummary={capability_code:string;consumed_units:number;reserved_units:number;periodic_units:number;addon_units:number;emergency_units:number;overage_units:number};
type AllowanceSummary={periods:{allowance_pool_code:string;period_starts_at:string;period_ends_at:string;allocation_type:string;granted_units:number;used:number}[];addons:{id:string;allowance_pool_code:string;granted_units:number;expires_at:string;active:boolean}[];addonPools:{allowance_pool_code:string;granted_units:number;used:number;remaining:number}[]};
const subscriptionStatus:Record<string,string>={TRIAL:'آزمایشی',ACTIVE:'فعال',PAST_DUE:'دارای بدهی',SUSPENDED:'تعلیق‌شده',CANCELLED:'لغوشده',EXPIRED:'منقضی'};
const n=(x:number)=>Number(x??0).toLocaleString('fa-IR'); const d=(x:string|null)=>x?new Date(x).toLocaleDateString('fa-IR'):'—';
const capabilityLabel=(code:string)=>({AI_TICKET_REVIEW:'بررسی هوشمند تیکت',AI_SMART_INTAKE:'تکمیل هوشمند درخواست'}[code]??'خدمت هوشمند سازمان');
export function OwnerCommercialDashboard({actor}:{actor:Actor}) {
  const [data,setData]=useState<Dashboard|null>(null),[actions,setActions]=useState<SmartActionSummary[]>([]),[allowance,setAllowance]=useState<AllowanceSummary|null>(null),[error,setError]=useState(''),[policy,setPolicy]=useState({capabilityCode:'',enabled:false,limitUnits:10}),[form,setForm]=useState({requestType:'ADDON',capabilityCode:'',requestedUnits:10,subscriptionId:'',requestNote:''});
  const load=()=>Promise.all([request('/platform/commercial/owner-dashboard',actor.session,actor.organizationId),request('/platform/commercial/owner/smart-actions',actor.session,actor.organizationId),request('/platform/commercial/owner/allowance-summary',actor.session,actor.organizationId)]).then(([dashboard,summary,allowanceSummary])=>{setData(dashboard as Dashboard);setActions(summary as SmartActionSummary[]);setAllowance(allowanceSummary as AllowanceSummary);}).catch(e=>setError(e instanceof Error?e.message:'دریافت نمای تجاری ناموفق بود.'));
  useEffect(()=>{void load();},[actor.organizationId,actor.session]);
  const send=async(e:FormEvent,path:string,body:unknown)=>{e.preventDefault();try{await request(path,actor.session,actor.organizationId,{method:'POST',headers:path.endsWith('requests')?{'idempotency-key':crypto.randomUUID()}:undefined,body:JSON.stringify(body)});await load();}catch(x){setError(x instanceof Error?x.message:'ثبت اطلاعات ناموفق بود.');}};
  if(error)return <p className="error" role="alert">{error}</p>; if(!data||!allowance)return <p className="hint">در حال دریافت اطلاعات…</p>;
  return <div className="admin-stack owner-commercial-dashboard">
    <section className="card"><div className="contextual-help-row"><div><h3>سهمیه و پشتیبانی</h3><p className="hint">ثبت دستی تیکت مستقل از سهمیهٔ اقدامات هوشمند است.</p></div><ContextualHelpTrigger actor={actor} relatedFeature="COMMERCIAL_DASHBOARD" label="راهنمای سهمیه و مصرف مازاد"/></div>{data.warnings?.length?<div className="notice warning">{data.warnings.map(x=><p key={x}>{x}</p>)}</div>:null}<h4>سرویس‌ها و اشتراک‌ها</h4><Table heads={['سرویس','وضعیت','پایان / مهلت','باقی‌مانده']} rows={data.subscriptions.map(x=>[x.product_name,subscriptionStatus[x.status]??x.status,x.status==='PAST_DUE'?d(x.grace_ends_at):d(x.ends_at),x.days_remaining===null?'—':`${n(x.days_remaining)} روز`])} empty="اشتراکی ثبت نشده است."/><p className="hint">تیکت‌گذاری دستی همیشه برقرار است، حتی وقتی دستیار هوشمند در دسترس نیست.</p></section>
    <section className="card"><h3>مصرف اقدامات هوشمند</h3><Table heads={['خدمت','مصرف‌شده','در انتظار','منبع مصرف']} rows={actions.map(x=>[capabilityLabel(x.capability_code),n(x.consumed_units),n(x.reserved_units),`دوره‌ای ${n(x.periodic_units)} · بسته ${n(x.addon_units)} · اضطراری ${n(x.emergency_units)} · مازاد ${n(x.overage_units)}`])} empty="مصرفی ثبت نشده است."/><p className="hint">هر تحلیل کامل درخواست یک اقدام است؛ تلاش مجدد، خطا و تبدیل صوتِ مستقل مصرف جداگانه ندارند.</p></section>
    <section className="card"><h3>ظرفیت و ترتیب مصرف</h3><p className="hint">سهمیه ماهانه ← بسته افزایشی ← سهمیه اضطراری ← مصرف مازاد ← توقف عملیات هوشمند</p><Table heads={['استخر','بازه UTC','کل / مصرف / باقی‌مانده','وضعیت']} rows={allowance.periods.filter(x=>x.allocation_type==='PERIODIC').map(x=>['عملیات هوشمند',`${d(x.period_starts_at)} تا ${d(x.period_ends_at)}`,`${n(x.granted_units)} / ${n(x.used)} / ${n(x.granted_units-x.used)}`,'سهمیه ماهانه'])} empty="سهمیه ماهانه‌ای برای این دوره ثبت نشده است."/><Table heads={['بسته افزایشی','کل / مصرف / باقی‌مانده']} rows={(allowance.addonPools??[]).map(x=>['عملیات هوشمند',`${n(x.granted_units)} / ${n(x.used)} / ${n(x.remaining)}`])} empty="بستهٔ افزایشی فعالی برای این دوره نیست."/><Table heads={['بسته افزایشی','ظرفیت','انقضا','وضعیت']} rows={allowance.addons.map(x=>['عملیات هوشمند',n(x.granted_units),d(x.expires_at),x.active?'فعال':'منقضی'])} empty="بسته افزایشی ثبت نشده است."/><Table heads={['سهمیه اضطراری','کل / مصرف / باقی‌مانده','وضعیت']} rows={allowance.periods.filter(x=>x.allocation_type==='EMERGENCY').map(x=>['عملیات هوشمند',`${n(x.granted_units)} / ${n(x.used)} / ${n(x.granted_units-x.used)}`,x.used>0?'شروع شده':'هنوز استفاده نشده'])} empty="سهمیه اضطراری برای این دوره ثبت نشده است."/><Table heads={['خدمت','مصرف مازاد']} rows={data.overage.map(x=>[capabilityLabel(x.capability_code),`${x.overage.enabled?'فعال':'غیرفعال'} · سقف ${n(x.overage.limit_units)} · مصرف ${n(x.overageUsed)} · باقی‌مانده ${n(Math.max(0,x.overage.limit_units-x.overageUsed))}`])} empty="مصرف مازادی ثبت نشده است."/><p className="hint">ظرفیت Assist: {n(data.assist?.capacity_units??0)} · پرونده‌های فعال: {n(data.assist?.active_cases??0)}</p><form className="compact-form" onSubmit={e=>void send(e,'/platform/commercial/owner/overage',policy)}><label>خدمت<select required value={policy.capabilityCode} onChange={e=>setPolicy({...policy,capabilityCode:e.target.value})}><option value="">انتخاب خدمت</option><option value="AI_TICKET_REVIEW">بررسی هوشمند تیکت</option><option value="AI_SMART_INTAKE">تکمیل هوشمند درخواست</option></select></label><label>وضعیت<select value={String(policy.enabled)} onChange={e=>setPolicy({...policy,enabled:e.target.value==='true'})}><option value="false">غیرفعال</option><option value="true">فعال</option></select></label><label>سقف<input type="number" min={policy.enabled?1:0} value={policy.limitUnits} onChange={e=>setPolicy({...policy,limitUnits:Number(e.target.value)})}/></label><button>ذخیرهٔ مصرف مازاد</button></form></section>
    <section className="card"><h3>درخواست تجاری</h3><form className="compact-form" onSubmit={e=>void send(e,'/platform/commercial/owner/requests',form)}><label>نوع<select value={form.requestType} onChange={e=>setForm({...form,requestType:e.target.value})}><option value="ADDON">بسته افزایشی</option><option value="RENEWAL">تمدید</option><option value="SERVICE_ACTIVATION">فعال‌سازی سرویس</option></select></label>{form.requestType!=='RENEWAL'&&<label>قابلیت<input dir="ltr" required value={form.capabilityCode} onChange={e=>setForm({...form,capabilityCode:e.target.value.toUpperCase()})}/></label>}{form.requestType==='ADDON'&&<label>واحد<input type="number" min="1" value={form.requestedUnits} onChange={e=>setForm({...form,requestedUnits:Number(e.target.value)})}/></label>}{form.requestType==='RENEWAL'&&<label>اشتراک<select required value={form.subscriptionId} onChange={e=>setForm({...form,subscriptionId:e.target.value})}><option value="">انتخاب کنید</option>{data.subscriptions.map(x=><option key={x.id} value={x.id}>{x.product_name}</option>)}</select></label>}<button>ارسال درخواست</button></form><Table heads={['نوع','وضعیت','نتیجه']} rows={data.requests.map(x=>[x.request_type,x.status,x.decision_note??'—'])} empty="درخواستی ثبت نشده است."/></section>
  </div>;
}
function Table({heads,rows,empty}:{heads:string[];rows:ReactNode[][];empty:string}){return <div className="table-wrap"><table><thead><tr>{heads.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>):<tr><td colSpan={heads.length}>{empty}</td></tr>}</tbody></table></div>}
