import { FormEvent, useEffect, useState } from 'react';
import type { Actor } from './App';
import { request } from './App';
import { applyPlatformAppearance, JUPITER_PRIMARY, type PlatformAppearanceValue as Appearance } from './AppearanceTokens';
import { AppearancePreview } from './AppearancePreview';
import { ContextualHelpTrigger } from './ContextualHelp';

const blank: Appearance = { brandPreset: 'JUPITER', densityPreset: 'STANDARD', radiusPreset: 'MEDIUM', logoUrl: null, customPrimary: null, effectivePrimary: JUPITER_PRIMARY, primarySource: 'SYSTEM', onPrimary: '#FFFFFF' };
const labels = { JUPITER: 'ژوپیتر آبی', OCEAN: 'آبی متین', TEAL: 'سبز نفتی', COMFORTABLE: 'راحت', STANDARD: 'استاندارد', COMPACT: 'فشرده', SMALL: 'کوچک', MEDIUM: 'متوسط', LARGE: 'بزرگ', SYSTEM: 'پیش‌فرض ژوپیتر', PLATFORM: 'پلتفرم', ORGANIZATION: 'سازمان' } as const;
const hex = (value: string) => /^#[0-9a-fA-F]{6}$/.test(value.trim());

export function PlatformAppearance({ actor, onSaved, onError }: { actor: Actor; onSaved: (message: string) => void; onError: (message: string) => void }) {
  const [value, setValue] = useState<Appearance>(blank);
  const [loading, setLoading] = useState(true);
  const load = () => request('/appearance', actor.session, actor.organizationId).then((next) => { const safe = next as Appearance; setValue(safe); applyPlatformAppearance(safe); }).catch((cause) => onError(cause instanceof Error ? cause.message : 'دریافت تنظیمات ظاهر ناموفق بود.')).finally(() => setLoading(false));
  useEffect(() => { void load(); }, [actor.session.accessToken]);
  const customInput = value.customPrimary ?? '';
  const save = async (event: FormEvent) => { event.preventDefault(); if (customInput && !hex(customInput)) { onError('رنگ باید در قالب #RRGGBB وارد شود.'); return; } try { const next = await request('/appearance', actor.session, actor.organizationId, { method: 'POST', body: JSON.stringify({ ...value, customPrimary: customInput || null }) }) as Appearance; setValue(next); applyPlatformAppearance(next); onSaved('ظاهر و هویت بصری پلتفرم به‌روزرسانی شد.'); } catch (cause) { onError(cause instanceof Error ? cause.message : 'ذخیره تنظیمات ظاهر ناموفق بود.'); } };
  const reset = async () => { try { const next = await request('/appearance/reset-primary', actor.session, actor.organizationId, { method: 'POST' }) as Appearance; setValue(next); applyPlatformAppearance(next); onSaved('رنگ سفارشی حذف شد و preset فعلی حفظ شد.'); } catch (cause) { onError(cause instanceof Error ? cause.message : 'حذف رنگ سفارشی ناموفق بود.'); } };
  if (loading) return <p className="hint" role="status">در حال دریافت تنظیمات ظاهر…</p>;
  const previewPrimary = customInput || value.effectivePrimary || JUPITER_PRIMARY;
  return <section className="card platform-appearance"><div className="ui-section-header"><div><h3>ظاهر و هویت بصری</h3><p className="hint">رنگ اصلی فقط tokenهای primary را تغییر می‌دهد؛ رنگ‌های موفقیت، هشدار و خطا مستقل می‌مانند.</p></div><ContextualHelpTrigger actor={actor} relatedFeature="PLATFORM_APPEARANCE" label="راهنمای ظاهر"/></div><form onSubmit={save} className="compact-form"><label>preset رنگ<select value={value.brandPreset} onChange={(event) => setValue({ ...value, brandPreset: event.target.value as Appearance['brandPreset'], effectivePrimary: undefined })}>{(['JUPITER','OCEAN','TEAL'] as const).map((item) => <option key={item} value={item}>{labels[item]}</option>)}</select></label><label>رنگ اصلی سفارشی<input dir="ltr" value={customInput} onChange={(event) => setValue({ ...value, customPrimary: event.target.value || null, effectivePrimary: event.target.value || undefined })} placeholder="#315399" aria-invalid={Boolean(customInput && !hex(customInput))}/>{customInput && !hex(customInput) && <small className="error">رنگ باید در قالب #RRGGBB وارد شود.</small>}</label><p className="hint">رنگ مؤثر: <b dir="ltr">{previewPrimary}</b> · منبع: {labels[value.primarySource ?? 'SYSTEM']}</p><AppearancePreview primary={previewPrimary}/><label>تراکم نمایش<select value={value.densityPreset} onChange={(event) => setValue({ ...value, densityPreset: event.target.value as Appearance['densityPreset'] })}>{(['COMFORTABLE','STANDARD','COMPACT'] as const).map((item) => <option key={item} value={item}>{labels[item]}</option>)}</select></label><label>گردی گوشه‌ها<select value={value.radiusPreset} onChange={(event) => setValue({ ...value, radiusPreset: event.target.value as Appearance['radiusPreset'] })}>{(['SMALL','MEDIUM','LARGE'] as const).map((item) => <option key={item} value={item}>{labels[item]}</option>)}</select></label><label>نشانی لوگوی پیش‌فرض (داخلی)<input dir="ltr" value={value.logoUrl ?? ''} onChange={(event) => setValue({ ...value, logoUrl: event.target.value || null })} placeholder="/jupiter-logo.png" pattern="/[A-Za-z0-9._/-]{1,512}" /></label><div className="inline-actions"><button disabled={Boolean(customInput && !hex(customInput))}>ذخیرهٔ ظاهر</button><button type="button" className="secondary" onClick={() => void reset()}>حذف رنگ سفارشی</button></div></form><p className="hint">حذف رنگ سفارشی preset، تراکم، radius و لوگو را تغییر نمی‌دهد. فقط #RRGGBB پذیرفته می‌شود؛ CSS یا JavaScript دلخواه پذیرفته نمی‌شود و کنتراست در سرور دوباره بررسی می‌شود.</p></section>;
}
