import { FormEvent, useEffect, useState } from 'react';
import type { Actor } from './App';
import { request } from './App';
import { ConfirmDialog } from './ui';

type Organization={id:string;name:string;slug:string;status:'active'|'suspended';created_at:string}; type User={id:string;email:string;display_name:string;is_platform_admin:boolean;is_active:boolean}; type AiSetting={organization_id:string;name:string;slug:string;enabled:boolean;model:string;updated_at?:string;requests?:number}; type Audit={id:string;action:string;organization_name?:string;actor_display_name?:string;created_at:string};

export function PlatformPro({actor}:{actor:Actor}){const [tab,setTab]=useState<'orgs'|'users'|'ai'|'audit'>('orgs');const [organizations,setOrganizations]=useState<Organization[]>([]);const [users,setUsers]=useState<User[]>([]);const [settings,setSettings]=useState<AiSetting[]>([]);const [audit,setAudit]=useState<Audit[]>([]);const [error,setError]=useState('');const [notice,setNotice]=useState('');const load=()=>Promise.all([request('/admin/platform/organizations',actor.session,actor.organizationId),request('/admin/platform/users',actor.session,actor.organizationId),request('/platform/ai-settings',actor.session,actor.organizationId),request('/platform/ai-settings/audit',actor.session,actor.organizationId)]).then(([orgs,nextUsers,nextSettings,nextAudit])=>{setOrganizations(orgs as Organization[]);setUsers(nextUsers as User[]);setSettings(nextSettings as AiSetting[]);setAudit(nextAudit as Audit[]);}).catch((cause)=>setError(cause.message));useEffect(()=>{void load();},[actor.session.accessToken]);return <section className="page platform-pro"><div className="page-intro"><div><p className="eyebrow">مدیریت پلتفرم</p><h2>کنترل امن سرویس و سازمان‌ها</h2><p>دسترسی‌ها، وضعیت سازمان‌ها و استفاده از هوش مصنوعی در سطح پلتفرم مدیریت می‌شوند.</p></div></div><div className="admin-tabs" role="tablist">{([['orgs','سازمان‌ها'],['users','کاربران پلتفرم'],['ai','سیاست AI'],['audit','ردپای ممیزی']] as const).map(([value,label])=><button type="button" key={value} className={tab===value?'active-tab':'secondary'} aria-selected={tab===value} onClick={()=>{setTab(value);setError('');}}>{label}</button>)}</div>{notice&&<p className="notice" role="status">{notice}</p>}{error&&<p className="error" role="alert">{error}</p>}{tab==='orgs'&&<Organizations actor={actor} organizations={organizations} onSaved={(message)=>{setNotice(message);load();}} onError={setError}/>} {tab==='users'&&<PlatformUsers actor={actor} users={users} onSaved={(message)=>{setNotice(message);load();}} onError={setError}/>} {tab==='ai'&&<AiPolicies actor={actor} settings={settings} onSaved={(message)=>{setNotice(message);load();}} onError={setError}/>} {tab==='audit'&&<AuditList audit={audit}/>}</section>}

function Organizations({actor,organizations,onSaved,onError}:{actor:Actor;organizations:Organization[];onSaved:(message:string)=>void;onError:(message:string)=>void}){const [form,setForm]=useState({name:'',slug:''});const [pending,setPending]=useState<Organization|null>(null);const create=async(event:FormEvent)=>{event.preventDefault();try{await request('/admin/platform/organizations',actor.session,actor.organizationId,{method:'POST',body:JSON.stringify(form)});setForm({name:'',slug:''});onSaved('سازمان جدید ساخته شد.');}catch(cause){onError(cause instanceof Error?cause.message:'ساخت سازمان ناموفق بود.')}};const toggle=async()=>{if(!pending)return;try{await request(`/admin/platform/organizations/${pending.id}/status`,actor.session,actor.organizationId,{method:'POST',body:JSON.stringify({status:pending.status==='active'?'suspended':'active'})});setPending(null);onSaved('وضعیت سازمان به‌روزرسانی شد.');}catch(cause){onError(cause instanceof Error?cause.message:'به‌روزرسانی ناموفق بود.')}};return <><div className="admin-grid"><section className="card"><h3>سازمان‌های پلتفرم</h3><div className="table-wrap"><table><thead><tr><th>نام</th><th>شناسه</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>{organizations.map((org)=><tr key={org.id}><td>{org.name}</td><td dir="ltr">{org.slug}</td><td><span className={`status-pill ${org.status}`}>{org.status==='active'?'فعال':'معلق'}</span></td><td><button className="secondary" type="button" onClick={()=>setPending(org)}>{org.status==='active'?'تعلیق':'فعال‌سازی'}</button></td></tr>)}</tbody></table></div></section><section className="card"><h3>ساخت سازمان</h3><form onSubmit={create}><label>نام سازمان<input value={form.name} onChange={(event)=>setForm({...form,name:event.target.value})} required/></label><label>Slug یکتا<input dir="ltr" value={form.slug} onChange={(event)=>setForm({...form,slug:event.target.value.toLowerCase()})} placeholder="acme-support" required/></label><button>ساخت سازمان</button></form></section></div><ConfirmDialog open={Boolean(pending)} title={pending?.status==='active'?'تعلیق سازمان':'فعال‌سازی سازمان'} body={pending?.status==='active'?`تعلیق «${pending?.name}» دسترسی اعضای آن سازمان را متوقف می‌کند تا دوباره فعال شود.`:`«${pending?.name}» دوباره برای اعضای مجاز در دسترس قرار می‌گیرد.`} confirmLabel={pending?.status==='active'?'تعلیق سازمان':'فعال‌سازی'} danger={pending?.status==='active'} onConfirm={()=>void toggle()} onClose={()=>setPending(null)}/></>}

function PlatformUsers({actor,users,onSaved,onError}:{actor:Actor;users:User[];onSaved:(message:string)=>void;onError:(message:string)=>void}) {
  const [form,setForm]=useState({displayName:'',email:'',password:'',isPlatformAdmin:false});
  const [managed,setManaged]=useState<User|null>(null);
  const [password,setPassword]=useState('');
  const create=async(event:FormEvent)=>{event.preventDefault();try{await request('/admin/platform/users',actor.session,actor.organizationId,{method:'POST',body:JSON.stringify(form)});setForm({displayName:'',email:'',password:'',isPlatformAdmin:false});onSaved('کاربر پلتفرم ساخته شد.');}catch(cause){onError(cause instanceof Error?cause.message:'ساخت کاربر ناموفق بود.')}};
  const toggle=async(user:User)=>{try{await request(`/admin/platform/users/${user.id}`,actor.session,actor.organizationId,{method:'POST',body:JSON.stringify({isActive:!user.is_active})});onSaved('وضعیت کاربر تغییر کرد.');}catch(cause){onError(cause instanceof Error?cause.message:'به‌روزرسانی ناموفق بود.')}};
  const saveManagement=async()=>{if(!managed)return;try{await request(`/admin/platform/users/${managed.id}`,actor.session,actor.organizationId,{method:'POST',body:JSON.stringify({isActive:managed.is_active,password:password||undefined})});setPassword('');setManaged(null);onSaved('تنظیمات کاربر به‌روزرسانی شد.');}catch(cause){onError(cause instanceof Error?cause.message:'به‌روزرسانی ناموفق بود.')}};
  return <><div className="admin-grid"><section className="card"><h3>کاربران پلتفرم</h3><div className="table-wrap"><table><thead><tr><th>نام</th><th>ایمیل</th><th>دسترسی</th><th>وضعیت</th><th></th></tr></thead><tbody>{users.map((user)=><tr key={user.id}><td>{user.display_name}</td><td dir="ltr">{user.email}</td><td>{user.is_platform_admin?'مدیر پلتفرم':'کاربر عادی'}</td><td><span className={`status-pill ${user.is_active?'active':'inactive'}`}>{user.is_active?'فعال':'غیرفعال'}</span></td><td><div className="member-actions"><button className="secondary" type="button" onClick={()=>{setPassword('');setManaged(user);}}>مدیریت</button><button className="secondary" type="button" onClick={()=>toggle(user)}>{user.is_active?'غیرفعال‌سازی':'فعال‌سازی'}</button></div></td></tr>)}</tbody></table></div></section><section className="card"><h3>افزودن کاربر پلتفرم</h3><form onSubmit={create}><label>نام<input value={form.displayName} onChange={(event)=>setForm({...form,displayName:event.target.value})} required/></label><label>ایمیل<input type="email" value={form.email} onChange={(event)=>setForm({...form,email:event.target.value})} required/></label><label>رمز موقت<input type="password" minLength={10} value={form.password} onChange={(event)=>setForm({...form,password:event.target.value})} required/></label><label className="check-label"><input type="checkbox" checked={form.isPlatformAdmin} onChange={(event)=>setForm({...form,isPlatformAdmin:event.target.checked})}/>دسترسی مدیر پلتفرم</label><button>افزودن کاربر</button></form></section></div>{managed&&<section className="card"><h3>مدیریت حساب: {managed.display_name}</h3><p className="hint">رمز جدید را فقط در صورت نیاز وارد کنید. با ذخیرهٔ آن، نشست‌های فعال این کاربر باطل می‌شوند.</p><label>رمز جدید (اختیاری)<input type="password" minLength={10} value={password} onChange={(event)=>setPassword(event.target.value)} autoComplete="new-password"/></label><div className="inline-actions"><button type="button" onClick={saveManagement} disabled={password.length>0&&password.length<10}>ذخیره</button><button type="button" className="secondary" onClick={()=>{setPassword('');setManaged(null);}}>انصراف</button></div></section>}</>;
}

function AiPolicies({actor,settings,onSaved,onError}:{actor:Actor;settings:AiSetting[];onSaved:(message:string)=>void;onError:(message:string)=>void}){const [models,setModels]=useState<Record<string,string>>({});const save=async(setting:AiSetting)=>{try{await request('/platform/ai-settings',actor.session,actor.organizationId,{method:'PUT',body:JSON.stringify({organizationId:setting.organization_id,enabled:!setting.enabled,model:models[setting.organization_id]??setting.model})});onSaved('سیاست AI ذخیره شد.');}catch(cause){onError(cause instanceof Error?cause.message:'ذخیره سیاست AI ناموفق بود.')}};return <section className="card"><h3>سیاست و مصرف هوش مصنوعی</h3><p className="hint">فعال‌سازی AI فقط مجوز قابلیت را تعیین می‌کند؛ هر پیشنهاد همچنان نیازمند تأیید کاربر است.</p><div className="table-wrap"><table><thead><tr><th>سازمان</th><th>مدل</th><th>درخواست‌ها</th><th>وضعیت</th><th></th></tr></thead><tbody>{settings.map((setting)=><tr key={setting.organization_id}><td>{setting.name}</td><td><input dir="ltr" value={models[setting.organization_id]??setting.model} onChange={(event)=>setModels({...models,[setting.organization_id]:event.target.value})}/></td><td>{setting.requests??0}</td><td><span className={`status-pill ${setting.enabled?'active':'inactive'}`}>{setting.enabled?'فعال':'غیرفعال'}</span></td><td><button type="button" className="secondary" onClick={()=>save(setting)}>{setting.enabled?'غیرفعال‌سازی':'فعال‌سازی و ذخیره'}</button></td></tr>)}</tbody></table></div></section>}
function AuditList({audit}:{audit:Audit[]}){return <section className="card"><h3>ردپای ممیزی AI و تبدیل صوت</h3><div className="table-wrap"><table><thead><tr><th>رویداد</th><th>سازمان</th><th>عامل</th><th>زمان</th></tr></thead><tbody>{audit.map((item)=><tr key={item.id}><td>{item.action}</td><td>{item.organization_name??'پلتفرم'}</td><td>{item.actor_display_name??'سامانه'}</td><td>{new Date(item.created_at).toLocaleString('fa-IR')}</td></tr>)}{!audit.length&&<tr><td colSpan={4}>رویدادی ثبت نشده است.</td></tr>}</tbody></table></div></section>}
