import { FormEvent, useEffect, useState } from 'react';
import type { Actor } from './App';
import { request } from './App';
import { ConfirmDialog } from './ui';

type Organization={id:string;name:string;slug:string;status:'active'|'suspended';created_at:string}; type User={id:string;email:string;display_name:string;is_platform_admin:boolean;is_active:boolean}; type AiSetting={organizationId:string;name:string;slug:string;enabled:boolean;providerBaseUrl:string;analysisModel:string;transcriptionModel:string;hasApiKey:boolean;updatedAt?:string;requestCount:number;tokenCount:number}; type Audit={id:string;action:string;organization_name?:string;actor_display_name?:string;created_at:string};

export function PlatformPro({actor}:{actor:Actor}){const [tab,setTab]=useState<'orgs'|'users'|'ai'|'audit'>('orgs');const [organizations,setOrganizations]=useState<Organization[]>([]);const [users,setUsers]=useState<User[]>([]);const [settings,setSettings]=useState<AiSetting[]>([]);const [audit,setAudit]=useState<Audit[]>([]);const [error,setError]=useState('');const [notice,setNotice]=useState('');const load=()=>Promise.all([request('/admin/platform/organizations',actor.session,actor.organizationId),request('/admin/platform/users',actor.session,actor.organizationId),request('/platform/ai-settings',actor.session,actor.organizationId),request('/platform/ai-settings/audit',actor.session,actor.organizationId)]).then(([orgs,nextUsers,nextSettings,nextAudit])=>{setOrganizations(orgs as Organization[]);setUsers(nextUsers as User[]);setSettings(nextSettings as AiSetting[]);setAudit(nextAudit as Audit[]);}).catch((cause)=>setError(cause.message));useEffect(()=>{void load();},[actor.session.accessToken]);return <section className="page platform-pro"><div className="page-intro"><div><p className="eyebrow">مدیریت پلتفرم</p><h2>کنترل امن سرویس و سازمان‌ها</h2><p>دسترسی‌ها، وضعیت سازمان‌ها و استفاده از هوش مصنوعی در سطح پلتفرم مدیریت می‌شوند.</p></div></div><div className="admin-tabs" role="tablist">{([['orgs','سازمان‌ها'],['users','کاربران پلتفرم'],['ai','سیاست AI'],['audit','ردپای ممیزی']] as const).map(([value,label])=><button type="button" key={value} className={tab===value?'active-tab':'secondary'} aria-selected={tab===value} onClick={()=>{setTab(value);setError('');}}>{label}</button>)}</div>{notice&&<p className="notice" role="status">{notice}</p>}{error&&<p className="error" role="alert">{error}</p>}{tab==='orgs'&&<Organizations actor={actor} organizations={organizations} onSaved={(message)=>{setNotice(message);load();}} onError={setError}/>} {tab==='users'&&<PlatformUsers actor={actor} users={users} onSaved={(message)=>{setNotice(message);load();}} onError={setError}/>} {tab==='ai'&&<AiPolicies actor={actor} settings={settings} onSaved={(message)=>{setNotice(message);load();}} onError={setError}/>} {tab==='audit'&&<AuditList audit={audit}/>}</section>}

function Organizations({actor,organizations,onSaved,onError}:{actor:Actor;organizations:Organization[];onSaved:(message:string)=>void;onError:(message:string)=>void}){const [form,setForm]=useState({name:'',slug:''});const [pending,setPending]=useState<Organization|null>(null);const create=async(event:FormEvent)=>{event.preventDefault();try{await request('/admin/platform/organizations',actor.session,actor.organizationId,{method:'POST',body:JSON.stringify(form)});setForm({name:'',slug:''});onSaved('سازمان جدید ساخته شد.');}catch(cause){onError(cause instanceof Error?cause.message:'ساخت سازمان ناموفق بود.')}};const toggle=async()=>{if(!pending)return;try{await request(`/admin/platform/organizations/${pending.id}/status`,actor.session,actor.organizationId,{method:'POST',body:JSON.stringify({status:pending.status==='active'?'suspended':'active'})});setPending(null);onSaved('وضعیت سازمان به‌روزرسانی شد.');}catch(cause){onError(cause instanceof Error?cause.message:'به‌روزرسانی ناموفق بود.')}};return <><div className="admin-grid"><section className="card"><h3>سازمان‌های پلتفرم</h3><div className="table-wrap"><table><thead><tr><th>نام</th><th>شناسه</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>{organizations.map((org)=><tr key={org.id}><td>{org.name}</td><td dir="ltr">{org.slug}</td><td><span className={`status-pill ${org.status}`}>{org.status==='active'?'فعال':'معلق'}</span></td><td><button className="secondary" type="button" onClick={()=>setPending(org)}>{org.status==='active'?'تعلیق':'فعال‌سازی'}</button></td></tr>)}</tbody></table></div></section><section className="card"><h3>ساخت سازمان</h3><form onSubmit={create}><label>نام سازمان<input value={form.name} onChange={(event)=>setForm({...form,name:event.target.value})} required/></label><label>Slug یکتا<input dir="ltr" value={form.slug} onChange={(event)=>setForm({...form,slug:event.target.value.toLowerCase()})} placeholder="acme-support" required/></label><button>ساخت سازمان</button></form></section></div><ConfirmDialog open={Boolean(pending)} title={pending?.status==='active'?'تعلیق سازمان':'فعال‌سازی سازمان'} body={pending?.status==='active'?`تعلیق «${pending?.name}» دسترسی اعضای آن سازمان را متوقف می‌کند تا دوباره فعال شود.`:`«${pending?.name}» دوباره برای اعضای مجاز در دسترس قرار می‌گیرد.`} confirmLabel={pending?.status==='active'?'تعلیق سازمان':'فعال‌سازی'} danger={pending?.status==='active'} onConfirm={()=>void toggle()} onClose={()=>setPending(null)}/></>}

function PlatformUsers({actor,users,onSaved,onError}:{actor:Actor;users:User[];onSaved:(message:string)=>void;onError:(message:string)=>void}) {
  const [form,setForm]=useState({displayName:'',email:'',password:'',isPlatformAdmin:false});
  const [managed,setManaged]=useState<User|null>(null);
  const [password,setPassword]=useState('');
  const create=async(event:FormEvent)=>{event.preventDefault();try{await request('/admin/platform/users',actor.session,actor.organizationId,{method:'POST',body:JSON.stringify(form)});setForm({displayName:'',email:'',password:'',isPlatformAdmin:false});onSaved('کاربر پلتفرم ساخته شد.');}catch(cause){onError(cause instanceof Error?cause.message:'ساخت کاربر ناموفق بود.')}};
  const toggle=async(user:User)=>{try{await request(`/admin/platform/users/${user.id}`,actor.session,actor.organizationId,{method:'POST',body:JSON.stringify({isActive:!user.is_active})});onSaved('وضعیت کاربر تغییر کرد.');}catch(cause){onError(cause instanceof Error?cause.message:'به‌روزرسانی ناموفق بود.')}};
  const saveManagement=async()=>{if(!managed)return;try{await request(`/admin/platform/users/${managed.id}`,actor.session,actor.organizationId,{method:'POST',body:JSON.stringify({isActive:managed.is_active,password:password||undefined})});setPassword('');setManaged(null);onSaved('تنظیمات کاربر به‌روزرسانی شد.');}catch(cause){onError(cause instanceof Error?cause.message:'به‌روزرسانی ناموفق بود.')}};
  return <><div className="admin-grid"><section className="card"><h3>کاربران پلتفرم</h3><div className="table-wrap"><table><thead><tr><th>نام</th><th>ایمیل</th><th>دسترسی</th><th>وضعیت</th><th></th></tr></thead><tbody>{users.map((user)=><tr key={user.id}><td>{user.display_name}</td><td dir="ltr">{user.email}</td><td>{user.is_platform_admin?'مدیر پلتفرم':'کاربر عادی'}</td><td><span className={`status-pill ${user.is_active?'active':'inactive'}`}>{user.is_active?'فعال':'غیرفعال'}</span></td><td><div className="member-actions"><button className="secondary" type="button" onClick={()=>{setPassword('');setManaged(user);}}>مدیریت</button><button className="secondary" type="button" onClick={()=>toggle(user)}>{user.is_active?'غیرفعال‌سازی':'فعال‌سازی'}</button></div></td></tr>)}</tbody></table></div></section><section className="card"><h3>افزودن کاربر پلتفرم</h3><form onSubmit={create}><label>نام<input value={form.displayName} onChange={(event)=>setForm({...form,displayName:event.target.value})} required/></label><label>ایمیل<input type="email" value={form.email} onChange={(event)=>setForm({...form,email:event.target.value})} required/></label><label>رمز موقت<input type="password" minLength={10} value={form.password} onChange={(event)=>setForm({...form,password:event.target.value})} required/></label><label className="check-label"><input type="checkbox" checked={form.isPlatformAdmin} onChange={(event)=>setForm({...form,isPlatformAdmin:event.target.checked})}/>دسترسی مدیر پلتفرم</label><button>افزودن کاربر</button></form></section></div>{managed&&<section className="card"><h3>مدیریت حساب: {managed.display_name}</h3><p className="hint">رمز جدید را فقط در صورت نیاز وارد کنید. با ذخیرهٔ آن، نشست‌های فعال این کاربر باطل می‌شوند.</p><label>رمز جدید (اختیاری)<input type="password" minLength={10} value={password} onChange={(event)=>setPassword(event.target.value)} autoComplete="new-password"/></label><div className="inline-actions"><button type="button" onClick={saveManagement} disabled={password.length>0&&password.length<10}>ذخیره</button><button type="button" className="secondary" onClick={()=>{setPassword('');setManaged(null);}}>انصراف</button></div></section>}</>;
}

type AiDraft={enabled:boolean;providerBaseUrl:string;analysisModel:string;transcriptionModel:string;apiKey:string};
type AiConnectionTest={success:boolean;code:string;message:string};
function AiPolicies({actor,settings,onSaved,onError}:{actor:Actor;settings:AiSetting[];onSaved:(message:string)=>void;onError:(message:string)=>void}){
  const [selectedId,setSelectedId]=useState('');
  const [draft,setDraft]=useState<AiDraft>({enabled:false,providerBaseUrl:'https://api.openai.com/v1',analysisModel:'gpt-4.1-mini',transcriptionModel:'gpt-4o-mini-transcribe',apiKey:''});
  const [removePending,setRemovePending]=useState(false);
  const [testing,setTesting]=useState(false);
  const [testResult,setTestResult]=useState<AiConnectionTest|null>(null);
  const selected=settings.find((item)=>item.organizationId===selectedId)??settings[0];
  useEffect(()=>{if(!selected)return;setSelectedId(selected.organizationId);setDraft({enabled:selected.enabled,providerBaseUrl:selected.providerBaseUrl,analysisModel:selected.analysisModel,transcriptionModel:selected.transcriptionModel,apiKey:''});setTestResult(null);},[selected?.organizationId,selected?.updatedAt]);
  const save=async(removeApiKey=false)=>{if(!selected)return;try{await request('/platform/ai-settings',actor.session,actor.organizationId,{method:'PUT',body:JSON.stringify({organizationId:selected.organizationId,enabled:removeApiKey?false:draft.enabled,providerBaseUrl:draft.providerBaseUrl,analysisModel:draft.analysisModel,transcriptionModel:draft.transcriptionModel,apiKey:draft.apiKey||undefined,removeApiKey})});setDraft({...draft,apiKey:'',enabled:removeApiKey?false:draft.enabled});setTestResult(null);setRemovePending(false);onSaved(removeApiKey?'کلید API حذف و قابلیت AI غیرفعال شد.':'تنظیمات امن AI ذخیره شد.');}catch(cause){onError(cause instanceof Error?cause.message:'ذخیره تنظیمات AI ناموفق بود.')}};
  const testConnection=async()=>{if(!selected)return;setTesting(true);setTestResult(null);try{setTestResult(await request('/platform/ai-settings/test',actor.session,actor.organizationId,{method:'POST',body:JSON.stringify({organizationId:selected.organizationId})}) as AiConnectionTest);}catch(cause){onError(cause instanceof Error?cause.message:'آزمون اتصال AI ناموفق بود.');}finally{setTesting(false);}};
  return <><div className="admin-grid"><section className="card"><h3>سازمان و مصرف AI</h3><p className="hint">تنظیم credentials فقط برای مدیر پلتفرم قابل دسترسی است.</p><label>سازمان<select value={selected?.organizationId??''} onChange={(event)=>setSelectedId(event.target.value)}>{settings.map((item)=><option key={item.organizationId} value={item.organizationId}>{item.name}</option>)}</select></label>{selected&&<dl className="summary-list"><div><dt>وضعیت کلید</dt><dd><span className={`status-pill ${selected.hasApiKey?'active':'inactive'}`}>{selected.hasApiKey?'تنظیم شده':'تنظیم نشده'}</span></dd></div><div><dt>درخواست‌ها</dt><dd>{selected.requestCount}</dd></div><div><dt>توکن ثبت‌شده</dt><dd>{selected.tokenCount}</dd></div></dl>}</section><section className="card"><h3>ارائه‌دهنده OpenAI-compatible</h3><p className="hint">کلید ذخیره‌شده هرگز نمایش داده نمی‌شود. خالی گذاشتن فیلد کلید، مقدار قبلی را حفظ می‌کند.</p><form onSubmit={(event)=>{event.preventDefault();void save();}}><label className="check-label"><input type="checkbox" checked={draft.enabled} onChange={(event)=>setDraft({...draft,enabled:event.target.checked})}/>فعال‌سازی AI برای این سازمان</label><label>Base URL<input dir="ltr" type="url" value={draft.providerBaseUrl} onChange={(event)=>setDraft({...draft,providerBaseUrl:event.target.value})} required/></label><label>مدل تحلیل<input dir="ltr" value={draft.analysisModel} onChange={(event)=>setDraft({...draft,analysisModel:event.target.value})} required/></label><label>مدل تبدیل صوت<input dir="ltr" value={draft.transcriptionModel} onChange={(event)=>setDraft({...draft,transcriptionModel:event.target.value})} required/></label><label>API key جدید (اختیاری)<input dir="ltr" type="password" autoComplete="new-password" value={draft.apiKey} onChange={(event)=>setDraft({...draft,apiKey:event.target.value})} placeholder={selected?.hasApiKey?'برای حفظ کلید فعلی خالی بگذارید':'کلید سازمان را وارد کنید'}/></label><div className="inline-actions"><button type="submit">ذخیره تنظیمات</button><button type="button" className="secondary" onClick={()=>void testConnection()} disabled={testing}>{testing?'در حال آزمون…':'آزمون اتصال'}</button>{selected?.hasApiKey&&<button type="button" className="secondary" onClick={()=>setRemovePending(true)}>حذف کلید</button>}</div></form><p className="hint">پس از ذخیرهٔ تنظیمات، «آزمون اتصال» فقط Base URL، کلید API و مدل تحلیل ذخیره‌شده را با یک درخواست کوتاه بررسی می‌کند؛ کلید نمایش یا ثبت نمی‌شود.</p>{testResult&&<p className={testResult.success?'notice':'error'} role={testResult.success?'status':'alert'}>{testResult.message}</p>}</section></div><ConfirmDialog open={removePending} title="حذف کلید API" body="کلید این سازمان به‌صورت غیرقابل‌بازگشت حذف و قابلیت AI غیرفعال می‌شود." confirmLabel="حذف کلید" danger onConfirm={()=>void save(true)} onClose={()=>setRemovePending(false)}/></>;
}
function AuditList({audit}:{audit:Audit[]}){return <section className="card"><h3>ردپای ممیزی AI و تبدیل صوت</h3><div className="table-wrap"><table><thead><tr><th>رویداد</th><th>سازمان</th><th>عامل</th><th>زمان</th></tr></thead><tbody>{audit.map((item)=><tr key={item.id}><td>{item.action}</td><td>{item.organization_name??'پلتفرم'}</td><td>{item.actor_display_name??'سامانه'}</td><td>{new Date(item.created_at).toLocaleString('fa-IR')}</td></tr>)}{!audit.length&&<tr><td colSpan={4}>رویدادی ثبت نشده است.</td></tr>}</tbody></table></div></section>}
