import { useEffect, useMemo, useState } from 'react';
import type { Actor } from './App';
import { request } from './App';

type Summary={total_tickets:number;active_tickets:number;completed_tickets:number;average_satisfaction:string;sla_breaches:number};
type Breakdown={status:{label:string;count:number}[];priority:{label:string;count:number}[];trend:{day:string;created:number;completed:number}[];tickets:{ticket_number:number;title:string;status:string;priority:string;created_at:string}[]};
const labels:Record<string,string>={OPEN:'باز',IN_PROGRESS:'در حال رسیدگی',WAITING_FOR_REQUESTER:'منتظر پاسخ',RESOLVED:'حل‌شده',CLOSED:'بسته',LOW:'کم',NORMAL:'عادی',HIGH:'بالا',URGENT:'فوری'};
const jalali=(value:string)=>new Intl.DateTimeFormat('fa-IR-u-ca-persian',{year:'numeric',month:'short',day:'numeric'}).format(new Date(`${value.slice(0,10)}T12:00:00`));

export function ReportsPro({actor}:{actor:Actor}) {
  const today=new Date().toISOString().slice(0,10); const monthAgo=new Date(Date.now()-29*86400000).toISOString().slice(0,10); const [from,setFrom]=useState(monthAgo); const [to,setTo]=useState(today); const [summary,setSummary]=useState<Summary|null>(null); const [breakdown,setBreakdown]=useState<Breakdown|null>(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
  const load=()=>{setLoading(true);setError('');const query=`from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`;Promise.all([request(`/reports/summary?${query}`,actor.session,actor.organizationId),request(`/reports/breakdown?${query}`,actor.session,actor.organizationId)]).then(([nextSummary,nextBreakdown])=>{setSummary(nextSummary as Summary);setBreakdown(nextBreakdown as Breakdown);}).catch(cause=>setError(cause.message)).finally(()=>setLoading(false));}; useEffect(()=>{void load();},[actor.organizationId]);
  const maximum=useMemo(()=>Math.max(1,...(breakdown?.trend.flatMap(row=>[row.created,row.completed])??[1])),[breakdown]); const preset=(days:number)=>{setFrom(new Date(Date.now()-(days-1)*86400000).toISOString().slice(0,10));setTo(today);};
  const exportCsv=async()=>{try{const query=`from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`;const csv=await request(`/reports/export?${query}`,actor.session,actor.organizationId) as string;const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`jupiter-report-${from}-to-${to}.csv`;link.click();URL.revokeObjectURL(url);}catch(cause){setError(cause instanceof Error?cause.message:'دریافت خروجی ناموفق بود.')}};
  return <section className="page reports-pro"><div className="page-intro"><div><p className="eyebrow">گزارش عملیاتی</p><h2>عملکرد خدمات در بازه انتخاب‌شده</h2><p>روند، ترکیب وضعیت و اولویت و فهرست قابل پیگیری تیکت‌ها.</p></div><button className="secondary" type="button" onClick={exportCsv}>دریافت CSV</button></div><section className="card report-controls"><div className="range-presets"><button className="secondary" type="button" onClick={()=>preset(7)}>۷ روز اخیر</button><button className="secondary" type="button" onClick={()=>preset(30)}>۳۰ روز اخیر</button></div><label>از تاریخ<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><small>{jalali(from)}</small></label><label>تا تاریخ<input type="date" value={to} onChange={e=>setTo(e.target.value)}/><small>{jalali(to)}</small></label><button type="button" onClick={load}>به‌روزرسانی</button></section>{error&&<p className="error" role="alert">{error}</p>}{loading&&<p className="hint">در حال تولید گزارش…</p>}{summary&&<div className="metric-grid"><Metric label="کل تیکت‌ها" value={summary.total_tickets} hint={`${jalali(from)} تا ${jalali(to)}`}/><Metric label="فعال" value={summary.active_tickets} hint="نیازمند پیگیری"/><Metric label="تکمیل‌شده" value={summary.completed_tickets} hint="حل یا بسته"/><Metric label="رضایت" value={summary.average_satisfaction} hint={`نقض SLA: ${summary.sla_breaches}`}/></div>}{breakdown&&<><div className="report-grid"><Distribution title="بر اساس وضعیت" rows={breakdown.status}/><Distribution title="بر اساس اولویت" rows={breakdown.priority}/></div><section className="card"><h3>روند روزانه</h3><p className="hint">ستون بنفش: ایجاد · ستون سبز: تکمیل</p><div className="trend-chart" aria-label="روند روزانه تیکت‌ها">{breakdown.trend.map(row=><div className="trend-day" key={row.day} title={`${jalali(row.day)}: ${row.created} ایجاد، ${row.completed} تکمیل`}><div className="trend-bars"><i className="created" style={{height:`${Math.max(4,row.created/maximum*100)}%`}}/><i className="completed" style={{height:`${Math.max(4,row.completed/maximum*100)}%`}}/></div><small>{jalali(row.day)}</small></div>)}</div></section><section className="card"><h3>تیکت‌های بازه</h3><div className="table-wrap"><table><thead><tr><th>شماره</th><th>عنوان</th><th>وضعیت</th><th>اولویت</th><th>ایجاد</th></tr></thead><tbody>{breakdown.tickets.map(ticket=><tr key={ticket.ticket_number}><td>#{ticket.ticket_number}</td><td>{ticket.title}</td><td>{labels[ticket.status]??'نامشخص'}</td><td>{labels[ticket.priority]??'نامشخص'}</td><td>{jalali(ticket.created_at)}</td></tr>)}{!breakdown.tickets.length&&<tr><td colSpan={5}>تیکتی در این بازه نیست.</td></tr>}</tbody></table></div></section></>}</section>;
}
function Metric({label,value,hint}:{label:string;value:string|number;hint:string}){return <article className="metric-card"><span>{label}</span><strong>{value}</strong><small>{hint}</small></article>}
function Distribution({title,rows}:{title:string;rows:{label:string;count:number}[]}){const max=Math.max(1,...rows.map(row=>row.count));return <section className="card distribution"><h3>{title}</h3>{rows.map(row=><div className="distribution-row" key={row.label}><span>{labels[row.label]??'نامشخص'}</span><div><i style={{width:`${row.count/max*100}%`}}/></div><strong>{row.count}</strong></div>)}{!rows.length&&<p className="hint">داده‌ای وجود ندارد.</p>}</section>}
