import { ForbiddenException, Injectable, OnModuleDestroy, OnModuleInit } from '@nestjs/common';
import { DatabaseService } from '../database/database.service.js';
import { NotificationService } from '../notifications/notification.service.js';

type Actor = { userId:string; organizationId:string; roles:string[] };
const managers = new Set(['ORG_ADMIN','SUPERVISOR']);

@Injectable()
export class SlaService implements OnModuleInit, OnModuleDestroy {
  private timer?: ReturnType<typeof setInterval>;
  constructor(private readonly database:DatabaseService, private readonly notifications:NotificationService) {}
  onModuleInit() { this.timer=setInterval(()=>void this.evaluateAll(),60_000); }
  onModuleDestroy() { if(this.timer) clearInterval(this.timer); }
  private manager(actor:Actor) { if(!actor.roles.some(role=>managers.has(role))) throw new ForbiddenException(); }
  async policies(actor:Actor) { this.manager(actor); return this.database.withOrganization(actor.organizationId,async c=>(await c.query('SELECT id,name,priority,first_response_minutes,resolution_minutes,warning_minutes,escalation_role,is_active FROM sla_policies ORDER BY priority')).rows); }
  async savePolicy(actor:Actor,input:{name:string;priority:'LOW'|'NORMAL'|'HIGH'|'URGENT';firstResponseMinutes:number;resolutionMinutes:number;warningMinutes:number;escalationRole:'SUPERVISOR'|'ORG_ADMIN';isActive?:boolean}) { this.manager(actor); return this.database.withOrganization(actor.organizationId,async c=>(await c.query('INSERT INTO sla_policies(organization_id,name,priority,first_response_minutes,resolution_minutes,warning_minutes,escalation_role,is_active) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(organization_id,priority) DO UPDATE SET name=EXCLUDED.name,first_response_minutes=EXCLUDED.first_response_minutes,resolution_minutes=EXCLUDED.resolution_minutes,warning_minutes=EXCLUDED.warning_minutes,escalation_role=EXCLUDED.escalation_role,is_active=EXCLUDED.is_active RETURNING id,name,priority,first_response_minutes,resolution_minutes,warning_minutes,escalation_role,is_active',[actor.organizationId,input.name,input.priority,input.firstResponseMinutes,input.resolutionMinutes,input.warningMinutes,input.escalationRole,input.isActive??true])).rows[0]); }
  async calendar(actor:Actor) { this.manager(actor); return this.database.withOrganization(actor.organizationId,async c=>(await c.query('SELECT timezone,workdays,start_minute,end_minute FROM business_calendars WHERE organization_id=$1',[actor.organizationId])).rows[0]??{timezone:'Asia/Tehran',workdays:[1,2,3,4,5],start_minute:480,end_minute:1020}); }
  async saveCalendar(actor:Actor,input:{timezone:string;workdays:number[];startMinute:number;endMinute:number}) { this.manager(actor); if(!input.workdays.length||input.workdays.some(day=>!Number.isInteger(day)||day<1||day>7)||input.endMinute<=input.startMinute) throw new ForbiddenException('Invalid business calendar'); return this.database.withOrganization(actor.organizationId,async c=>(await c.query('INSERT INTO business_calendars(organization_id,timezone,workdays,start_minute,end_minute) VALUES($1,$2,$3,$4,$5) ON CONFLICT(organization_id) DO UPDATE SET timezone=EXCLUDED.timezone,workdays=EXCLUDED.workdays,start_minute=EXCLUDED.start_minute,end_minute=EXCLUDED.end_minute,updated_at=now() RETURNING timezone,workdays,start_minute,end_minute',[actor.organizationId,input.timezone,input.workdays,input.startMinute,input.endMinute])).rows[0]); }
  async clocks(actor:Actor) { this.manager(actor); return this.database.withOrganization(actor.organizationId,async c=>(await c.query("SELECT t.id,t.ticket_number,t.title,t.status,c.first_response_due_at,c.resolution_due_at,c.first_response_at,c.resolved_at,c.warning_at,c.breached_at,c.escalated_at FROM ticket_sla_clocks c JOIN tickets t ON t.id=c.ticket_id WHERE t.status NOT IN ('CLOSED') ORDER BY c.resolution_due_at NULLS LAST")).rows); }
  async evaluateAll(now=new Date()) { const organizations=(await this.database.query<{id:string}>('SELECT id FROM organizations WHERE status=\'active\'')).rows; return Promise.all(organizations.map(org=>this.evaluateOrganization(org.id,now))); }
  async evaluateOrganization(organizationId:string,now=new Date()) { return this.database.withOrganization(organizationId,async c=>{ const affected=(await c.query<{ticket_id:string;ticket_number:number;escalation_role:string;stage:string}>(`WITH due AS (SELECT c.ticket_id,p.escalation_role,CASE WHEN c.breached_at IS NULL AND c.resolution_due_at IS NOT NULL AND c.resolution_due_at <= $1 THEN 'breach' WHEN c.warning_at IS NULL AND c.resolution_due_at IS NOT NULL AND c.resolution_due_at-$1::timestamptz <= make_interval(mins=>p.warning_minutes) THEN 'warning' END stage FROM ticket_sla_clocks c JOIN sla_policies p ON p.id=c.policy_id JOIN tickets t ON t.id=c.ticket_id WHERE t.status NOT IN ('RESOLVED','CLOSED')), changed AS (UPDATE ticket_sla_clocks c SET warning_at=CASE WHEN due.stage='warning' THEN $1 ELSE c.warning_at END,breached_at=CASE WHEN due.stage='breach' THEN $1 ELSE c.breached_at END,escalated_at=CASE WHEN due.stage='breach' THEN $1 ELSE c.escalated_at END FROM due WHERE c.ticket_id=due.ticket_id AND due.stage IS NOT NULL RETURNING c.ticket_id,due.escalation_role,due.stage) SELECT changed.ticket_id,t.ticket_number,changed.escalation_role,changed.stage FROM changed JOIN tickets t ON t.id=changed.ticket_id`,[now])).rows; for(const item of affected){await c.query('INSERT INTO audit_logs(organization_id,action,target_type,target_id,metadata) VALUES($1,$2,\'ticket\',$3,$4)',[organizationId,item.stage==='breach'?'sla.breached':'sla.warning',item.ticket_id,{ticketNumber:item.ticket_number}]);const recipients=(await c.query<{user_id:string}>(`SELECT DISTINCT m.user_id FROM memberships m JOIN membership_roles mr ON mr.membership_id=m.id JOIN roles r ON r.id=mr.role_id WHERE m.status='active' AND r.code=$1`,[item.escalation_role])).rows.map(row=>row.user_id);this.notifications.publish(organizationId,recipients,{type:`sla.${item.stage}`,ticketId:item.ticket_id,occurredAt:now.toISOString()});} return affected;}); }
}
