import { Body, Controller, Get, Headers, Param, Post } from '@nestjs/common';
import { TicketActorService } from '../tickets/ticket-actor.service.js';
import { DirectoryConnectorService } from './directory-connector.service.js';

@Controller('directory')
export class DirectoryConnectorController {
  constructor(private readonly actors: TicketActorService, private readonly connectors: DirectoryConnectorService) {}
  private actor(authorization?: string, organizationId?: string) { return this.actors.fromHeaders(authorization,organizationId); }

  @Get('connectors') list(@Headers('authorization') authorization?:string,@Headers('x-organization-id') organizationId?:string) { return this.actor(authorization,organizationId).then(actor=>this.connectors.list(actor)); }
  @Post('connectors') create(@Body() body:{displayName?:string},@Headers('authorization') authorization?:string,@Headers('x-organization-id') organizationId?:string) { return this.actor(authorization,organizationId).then(actor=>this.connectors.create(actor,body.displayName)); }
  @Post('connectors/:id/pairings') pairing(@Param('id') id:string,@Headers('authorization') authorization?:string,@Headers('x-organization-id') organizationId?:string) { return this.actor(authorization,organizationId).then(actor=>this.connectors.createPairing(actor,id)); }
  @Post('connectors/:id/re-pair') rePair(@Param('id') id:string,@Headers('authorization') authorization?:string,@Headers('x-organization-id') organizationId?:string) { return this.actor(authorization,organizationId).then(actor=>this.connectors.rePair(actor,id)); }
  @Post('connectors/:id/revoke') revoke(@Param('id') id:string,@Headers('authorization') authorization?:string,@Headers('x-organization-id') organizationId?:string) { return this.actor(authorization,organizationId).then(actor=>this.connectors.revoke(actor,id)); }
  @Get('connectors/:id/sync-runs') runs(@Param('id') id:string,@Headers('authorization') authorization?:string,@Headers('x-organization-id') organizationId?:string) { return this.actor(authorization,organizationId).then(actor=>this.connectors.runs(actor,id)); }
  @Get('scope') scope(@Headers('authorization') authorization?:string,@Headers('x-organization-id') organizationId?:string) { return this.actor(authorization,organizationId).then(actor=>this.connectors.scope(actor)); }
  @Post('scope') saveScope(@Body() body:{scopeType?:string;selectedOuIds?:string[];selectedGroupIds?:string[]},@Headers('authorization') authorization?:string,@Headers('x-organization-id') organizationId?:string) { return this.actor(authorization,organizationId).then(actor=>this.connectors.saveScope(actor,body)); }
  @Get('mappings') mappings(@Headers('authorization') authorization?:string,@Headers('x-organization-id') organizationId?:string) { return this.actor(authorization,organizationId).then(actor=>this.connectors.mappings(actor)); }
  @Get('conflicts') conflicts(@Headers('x-directory-connector-id') connectorId?:string,@Headers('authorization') authorization?:string,@Headers('x-organization-id') organizationId?:string) { return this.actor(authorization,organizationId).then(actor=>this.connectors.conflicts(actor,connectorId)); }
  @Post('mappings') mapping(@Body() body:{groupExternalId?:string;roleCode?:string;enabled?:boolean},@Headers('authorization') authorization?:string,@Headers('x-organization-id') organizationId?:string) { return this.actor(authorization,organizationId).then(actor=>this.connectors.saveMapping(actor,body)); }
  @Post('connectors/:id/sync-now') syncNow(@Param('id') id:string,@Headers('idempotency-key') key?:string,@Headers('authorization') authorization?:string,@Headers('x-organization-id') organizationId?:string) { return this.actor(authorization,organizationId).then(actor=>this.connectors.syncNow(actor,id,key??'')); }
  @Post('agent/pair') pair(@Body() body:{pairingCode?:string;deviceName?:string}) { return this.connectors.pair(body.pairingCode,body.deviceName); }
  @Post('agent/heartbeat') heartbeat(@Body() body:{version?:string;policyVersion?:number;serviceStatus?:string},@Headers('authorization') authorization?:string,@Headers('x-directory-device-id') deviceId?:string,@Headers('x-directory-connector-id') connectorId?:string) { return this.connectors.heartbeat(connectorId,deviceId,authorization?.replace(/^Bearer\s+/i,''),body.version,body.policyVersion,body.serviceStatus); }
  @Post('agent/policy') policy(@Headers('authorization') authorization?:string,@Headers('x-directory-device-id') deviceId?:string,@Headers('x-directory-connector-id') connectorId?:string) { return this.connectors.agentPolicy(connectorId,deviceId,authorization?.replace(/^Bearer\s+/i,'')); }
  @Post('agent/scope-discovery') discovery(@Body() body:unknown,@Headers('authorization') authorization?:string,@Headers('x-directory-device-id') deviceId?:string,@Headers('x-directory-connector-id') connectorId?:string) { return this.connectors.discoverScope(connectorId,deviceId,authorization?.replace(/^Bearer\s+/i,''),body); }
  @Post('agent/sync/preview') preview(@Body() body:unknown,@Headers('authorization') authorization?:string,@Headers('x-directory-device-id') deviceId?:string,@Headers('x-directory-connector-id') connectorId?:string) { return this.connectors.preview(connectorId,deviceId,authorization?.replace(/^Bearer\s+/i,''),body); }
  @Post('agent/sync/validate-apply') validateApply(@Body() body:{runId?:string},@Headers('authorization') authorization?:string,@Headers('x-directory-device-id') deviceId?:string,@Headers('x-directory-connector-id') connectorId?:string) { return this.connectors.assertNoConflictsForApply(connectorId,deviceId,authorization?.replace(/^Bearer\s+/i,''),body.runId); }
  @Post('agent/sync/apply') apply(@Body() body:{runId?:string;commandId?:string},@Headers('authorization') authorization?:string,@Headers('x-directory-device-id') deviceId?:string,@Headers('x-directory-connector-id') connectorId?:string) { return this.connectors.applyOperational(connectorId,deviceId,authorization?.replace(/^Bearer\s+/i,''),body.runId,body.commandId); }
  @Post('agent/sync/apply-operational') applyOperational(@Body() body:{runId?:string;commandId?:string},@Headers('authorization') authorization?:string,@Headers('x-directory-device-id') deviceId?:string,@Headers('x-directory-connector-id') connectorId?:string) { return this.connectors.applyOperational(connectorId,deviceId,authorization?.replace(/^Bearer\s+/i,''),body.runId,body.commandId); }
  @Post('agent/sync/full-batch') fullBatch(@Body() body:unknown,@Headers('authorization') authorization?:string,@Headers('x-directory-device-id') deviceId?:string,@Headers('x-directory-connector-id') connectorId?:string) { return this.connectors.recordFullBatch(connectorId,deviceId,authorization?.replace(/^Bearer\s+/i,''),body); }
  @Post('agent/sync/full-complete') fullComplete(@Body() body:unknown,@Headers('authorization') authorization?:string,@Headers('x-directory-device-id') deviceId?:string,@Headers('x-directory-connector-id') connectorId?:string) { return this.connectors.completeFullReconciliation(connectorId,deviceId,authorization?.replace(/^Bearer\s+/i,''),body); }
  @Post('agent/sync/fail-command') failCommand(@Body() body:unknown,@Headers('authorization') authorization?:string,@Headers('x-directory-device-id') deviceId?:string,@Headers('x-directory-connector-id') connectorId?:string) { return this.connectors.failCommand(connectorId,deviceId,authorization?.replace(/^Bearer\s+/i,''),body); }
  @Post('agent/sync/record-failure') recordFailure(@Body() body:unknown,@Headers('authorization') authorization?:string,@Headers('x-directory-device-id') deviceId?:string,@Headers('x-directory-connector-id') connectorId?:string) { return this.connectors.recordSyncFailure(connectorId,deviceId,authorization?.replace(/^Bearer\s+/i,''),body); }
}
