import { BadRequestException, ForbiddenException, Injectable, NotFoundException, UnauthorizedException } from '@nestjs/common';
import { createHash, randomBytes, randomUUID, timingSafeEqual } from 'node:crypto';
import { DatabaseService } from '../database/database.service.js';

type Actor={userId:string;organizationId:string;roles:string[]};
type Connector={id:string;organization_id:string;display_name:string;status:'UNPAIRED'|'PAIRED'|'REVOKED';device_id:string|null;device_token_hash?:string|null;paired_at:string|null;last_seen_at:string|null;version:string|null;last_heartbeat_at:string|null;last_sync_at:string|null;last_sync_status:string|null;last_error_code:string|null;created_at:string};
type Db={query:<T=any>(sql:string,values?:unknown[])=>Promise<{rows:T[]}>};
type Entry={externalObjectId:string;accountName?:string|null;email?:string|null;displayName:string;givenName?:string|null;surname?:string|null;department?:string|null;title?:string|null;telephoneNumber?:string|null;manager?:string|null;memberOf?:string[];enabled:boolean;roles?:string[]};
type Plan={externalObjectId:string;action:'CREATE'|'UPDATE'|'SUSPEND'|'OUT_OF_SCOPE'|'UNCHANGED';entry?:Entry};
const roles=new Set(['REQUESTER','EXPERT','SUPERVISOR']);

@Injectable()
export class DirectoryConnectorService {
  constructor(private readonly database:DatabaseService) {}
  private hash(value:string){return createHash('sha256').update(value).digest('hex');}
  private secret(){return randomBytes(32).toString('base64url');}
  private manager(actor:Actor){if(!actor.roles.some(role=>role==='ORG_ADMIN'||role==='ORG_OWNER'))throw new ForbiddenException();}
  private audit(c:{query:(sql:string,values?:unknown[])=>Promise<unknown>},actor:Actor,action:string,id:string,metadata:object={}){return c.query('INSERT INTO audit_logs(organization_id,actor_user_id,action,target_type,target_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[actor.organizationId,actor.userId,action,'directory_connector',id,metadata]);}
  private equal(a:string,b:string){const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y);}
  private connectorName(value?:string){const result=value?.trim();if(!result||result.length<2||result.length>120)throw new BadRequestException('نام اتصال باید بین ۲ تا ۱۲۰ نویسه باشد.');return result;}

  async list(actor:Actor){this.manager(actor);return this.database.withOrganization(actor.organizationId,async c=>(await c.query<Connector>('SELECT id,organization_id,display_name,status,device_id,paired_at,last_seen_at,version,last_heartbeat_at,last_sync_at,last_sync_status,last_error_code,created_at FROM directory_connectors ORDER BY created_at DESC')).rows);}
  async runs(actor:Actor,id:string){this.manager(actor);return this.database.withOrganization(actor.organizationId,async c=>(await c.query('SELECT id,sync_kind,status,summary,error_code,created_at,applied_at FROM directory_sync_runs WHERE connector_id=$1 ORDER BY created_at DESC LIMIT 20',[id])).rows);}
  async create(actor:Actor,displayName?:string){this.manager(actor);return this.database.withOrganization(actor.organizationId,async c=>{const value=(await c.query<Connector>('INSERT INTO directory_connectors(organization_id,display_name,created_by_user_id) VALUES($1,$2,$3) RETURNING id,organization_id,display_name,status,device_id,paired_at,last_seen_at,version,last_heartbeat_at,last_sync_at,last_sync_status,last_error_code,created_at',[actor.organizationId,this.connectorName(displayName),actor.userId])).rows[0];await this.audit(c,actor,'directory_connector.created',value.id);return value;});}
  async createPairing(actor:Actor,id:string){this.manager(actor);const code=this.secret();return this.database.withOrganization(actor.organizationId,async c=>{const connector=(await c.query<{id:string;status:string}>('SELECT id,status FROM directory_connectors WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!connector)throw new NotFoundException('اتصال دایرکتوری یافت نشد.');if(connector.status==='REVOKED')throw new BadRequestException('اتصال لغوشده است و کد جدید دریافت نمی‌کند.');await c.query('UPDATE directory_connector_pairings SET consumed_at=now() WHERE connector_id=$1 AND consumed_at IS NULL',[id]);const row=(await c.query<{expires_at:string}>('INSERT INTO directory_connector_pairings(organization_id,connector_id,pairing_hash,expires_at,created_by_user_id) VALUES($1,$2,$3,now()+interval \'15 minutes\',$4) RETURNING expires_at',[actor.organizationId,id,this.hash(code),actor.userId])).rows[0];await this.audit(c,actor,'directory_connector.pairing_issued',id,{expiresAt:row.expires_at});return{connectorId:id,pairingCode:code,expiresAt:row.expires_at};});}
  async revoke(actor:Actor,id:string){this.manager(actor);return this.database.withOrganization(actor.organizationId,async c=>{const value=(await c.query<{id:string}>('UPDATE directory_connectors SET status=\'REVOKED\',device_token_hash=NULL,updated_at=now() WHERE id=$1 AND status<>\'REVOKED\' RETURNING id',[id])).rows[0];if(!value)throw new NotFoundException('اتصال فعال یافت نشد.');await c.query('UPDATE directory_connector_pairings SET consumed_at=COALESCE(consumed_at,now()) WHERE connector_id=$1',[id]);await this.audit(c,actor,'directory_connector.revoked',id);return{status:'REVOKED'};});}
  async pair(code?:string,deviceName?:string){if(!code||code.length<32||!deviceName?.trim()||deviceName.trim().length>120)throw new BadRequestException('کد جفت‌سازی یا نام دستگاه معتبر نیست.');const token=this.secret(),deviceId=randomUUID();return this.database.transaction(async c=>{const pairing=(await c.query<{id:string;organization_id:string;connector_id:string}>('SELECT id,organization_id,connector_id FROM directory_connector_pairings WHERE pairing_hash=$1 AND consumed_at IS NULL AND expires_at>now() FOR UPDATE',[this.hash(code)])).rows[0];if(!pairing)throw new BadRequestException('کد جفت‌سازی نامعتبر یا منقضی است.');const connector=(await c.query<{id:string;status:string}>('SELECT id,status FROM directory_connectors WHERE id=$1 AND organization_id=$2 FOR UPDATE',[pairing.connector_id,pairing.organization_id])).rows[0];if(!connector||connector.status==='REVOKED')throw new BadRequestException('این اتصال برای جفت‌سازی در دسترس نیست.');await c.query('UPDATE directory_connector_pairings SET consumed_at=now() WHERE id=$1',[pairing.id]);await c.query('UPDATE directory_connectors SET status=\'PAIRED\',device_id=$1,device_token_hash=$2,paired_at=now(),last_seen_at=now(),last_heartbeat_at=now(),updated_at=now() WHERE id=$3',[deviceId,this.hash(token),connector.id]);return{connectorId:connector.id,organizationId:pairing.organization_id,deviceId,deviceToken:token};});}

  private parse(value:unknown){const input=value as {requestId?:string;kind?:'FULL'|'DELTA';scopeFingerprint?:string;connectorVersion?:string;entries?:Entry[]};if(!input||!/^[0-9a-f-]{36}$/i.test(input.requestId??'')||!input.kind||!input.scopeFingerprint||input.scopeFingerprint.length<8||input.scopeFingerprint.length>256||!Array.isArray(input.entries)||input.entries.length>1000)throw new BadRequestException('درخواست همگام‌سازی معتبر نیست.');const seen=new Set<string>();for(const e of input.entries){if(!e||!e.externalObjectId||e.externalObjectId.length>512||seen.has(e.externalObjectId)||!e.displayName||e.displayName.trim().length<2||e.displayName.trim().length>160||typeof e.enabled!=='boolean'||(e.roles??[]).some(role=>!roles.has(role)))throw new BadRequestException('رکورد دایرکتوری معتبر نیست.');seen.add(e.externalObjectId);}return input as Required<Pick<typeof input,'requestId'|'kind'|'scopeFingerprint'|'entries'>>&typeof input;}
  private managed(e:Entry){return{givenName:e.givenName??null,surname:e.surname??null,department:e.department??null,title:e.title??null,telephoneNumber:e.telephoneNumber??null,manager:e.manager??null,memberOf:e.memberOf??[],enabled:e.enabled};}
  private async agent(connectorId:string|undefined,deviceId:string|undefined,token:string|undefined,work:(c:Db,connector:Connector)=>Promise<object>){if(!connectorId||!deviceId||!token)throw new UnauthorizedException('هویت عامل دایرکتوری معتبر نیست.');return this.database.transaction(async c=>{const connector=(await c.query<Connector>('SELECT id,organization_id,display_name,status,device_id,device_token_hash,paired_at,last_seen_at,version,last_heartbeat_at,last_sync_at,last_sync_status,last_error_code,created_at FROM directory_connectors WHERE id=$1 FOR UPDATE',[connectorId])).rows[0];if(!connector||connector.status!=='PAIRED'||connector.device_id!==deviceId||!connector.device_token_hash||!this.equal(connector.device_token_hash,this.hash(token)))throw new UnauthorizedException('هویت عامل دایرکتوری معتبر نیست.');const result=await work(c,connector);const next=this.secret();await c.query('UPDATE directory_connectors SET device_token_hash=$1,last_seen_at=now(),last_heartbeat_at=now(),updated_at=now() WHERE id=$2',[this.hash(next),connector.id]);return{...result,deviceToken:next};});}
  async heartbeat(id?:string,deviceId?:string,token?:string,version?:string){return this.agent(id,deviceId,token,async(c,connector)=>{if(version?.trim())await c.query('UPDATE directory_connectors SET version=$1 WHERE id=$2',[version.trim().slice(0,80),connector.id]);return{connectorId:connector.id,organizationId:connector.organization_id,status:'PAIRED'};});}
  async preview(id:string|undefined,deviceId:string|undefined,token:string|undefined,payload:unknown){const input=this.parse(payload);return this.agent(id,deviceId,token,async(c,connector)=>{const old=(await c.query<{id:string;summary:object}>('SELECT id,summary FROM directory_sync_runs WHERE connector_id=$1 AND request_id=$2',[connector.id,input.requestId])).rows[0];if(old)return{runId:old.id,status:'PREVIEWED',summary:old.summary,idempotent:true};const existing=(await c.query<{external_object_id:string;account_name:string|null;email:string|null;display_name:string;managed_fields:object;status:string}>('SELECT external_object_id,account_name,email,display_name,managed_fields,status FROM directory_principals WHERE organization_id=$1',[connector.organization_id])).rows;const previous=new Map(existing.map(row=>[row.external_object_id,row]));const plan:Plan[]=input.entries.map(entry=>{const current=previous.get(entry.externalObjectId);const changed=!current||current.account_name!==(entry.accountName?.toLowerCase()??null)||current.email!==(entry.email?.toLowerCase()??null)||current.display_name!==entry.displayName.trim()||JSON.stringify(current.managed_fields)!==JSON.stringify(this.managed(entry));return{externalObjectId:entry.externalObjectId,action:!entry.enabled?'SUSPEND':!current?'CREATE':changed||current.status!=='ACTIVE'?'UPDATE':'UNCHANGED',entry};});if(input.kind==='FULL'){const received=new Set(input.entries.map(x=>x.externalObjectId));for(const row of existing)if(!received.has(row.external_object_id)&&row.status!=='SUSPENDED')plan.push({externalObjectId:row.external_object_id,action:'OUT_OF_SCOPE'});}const summary=Object.fromEntries(['CREATE','UPDATE','SUSPEND','OUT_OF_SCOPE','UNCHANGED'].map(action=>[action.toLowerCase(),plan.filter(x=>x.action===action).length]));const run=(await c.query<{id:string}>('INSERT INTO directory_sync_runs(organization_id,connector_id,request_id,sync_kind,status,scope_fingerprint,plan,summary) VALUES($1,$2,$3,$4,\'PREVIEWED\',$5,$6,$7) RETURNING id',[connector.organization_id,connector.id,input.requestId,input.kind,input.scopeFingerprint,JSON.stringify(plan),JSON.stringify(summary)])).rows[0];if(input.connectorVersion?.trim())await c.query('UPDATE directory_connectors SET version=$1,last_sync_status=\'PREVIEWED\' WHERE id=$2',[input.connectorVersion.trim().slice(0,80),connector.id]);return{runId:run.id,status:'PREVIEWED',summary,idempotent:false};});}
  async apply(id:string|undefined,deviceId:string|undefined,token:string|undefined,runId?:string){if(!runId||!/^[0-9a-f-]{36}$/i.test(runId))throw new BadRequestException('شناسهٔ پیش‌نمایش معتبر نیست.');return this.agent(id,deviceId,token,async(c,connector)=>{const run=(await c.query<{id:string;status:string;plan:Plan[];summary:object}>('SELECT id,status,plan,summary FROM directory_sync_runs WHERE id=$1 AND connector_id=$2 AND organization_id=$3 FOR UPDATE',[runId,connector.id,connector.organization_id])).rows[0];if(!run)throw new NotFoundException('پیش‌نمایش همگام‌سازی یافت نشد.');if(run.status==='APPLIED')return{runId:run.id,status:'APPLIED',summary:run.summary,idempotent:true};for(const item of run.plan)await this.applyItem(c,connector.organization_id,item);await c.query('UPDATE directory_sync_runs SET status=\'APPLIED\',applied_at=now() WHERE id=$1',[run.id]);await c.query('UPDATE directory_connectors SET last_sync_at=now(),last_sync_status=\'SUCCEEDED\',last_error_code=NULL WHERE id=$1',[connector.id]);return{runId:run.id,status:'APPLIED',summary:run.summary,idempotent:false};});}
  private async applyItem(c:Db,org:string,item:Plan){if(item.action==='UNCHANGED')return;if(item.action==='OUT_OF_SCOPE'){const principal=(await c.query<{id:string;user_id:string|null;managed_fields:{outOfScopeAt?:string}}>('SELECT id,user_id,managed_fields FROM directory_principals WHERE organization_id=$1 AND external_object_id=$2 FOR UPDATE',[org,item.externalObjectId])).rows[0];if(!principal)return;const expired=principal.managed_fields.outOfScopeAt&&new Date(principal.managed_fields.outOfScopeAt).getTime()<=Date.now()-604800000;if(expired){await c.query('UPDATE directory_principals SET status=\'SUSPENDED\',updated_at=now() WHERE id=$1',[principal.id]);if(principal.user_id)await c.query('UPDATE memberships SET status=\'inactive\' WHERE organization_id=$1 AND user_id=$2',[org,principal.user_id]);}else await c.query('UPDATE directory_principals SET managed_fields=jsonb_set(managed_fields,\'{outOfScopeAt}\',to_jsonb(now()::text),true),updated_at=now() WHERE id=$1',[principal.id]);return;}const e=item.entry!;let principal=(await c.query<{id:string;user_id:string|null}>('SELECT id,user_id FROM directory_principals WHERE organization_id=$1 AND external_object_id=$2 FOR UPDATE',[org,e.externalObjectId])).rows[0];if(!principal){const user=(await c.query<{id:string}>('INSERT INTO users(email,display_name,password_hash) VALUES(NULL,$1,NULL) RETURNING id',[e.displayName.trim()])).rows[0];const member=(await c.query<{id:string}>('INSERT INTO memberships(organization_id,user_id,status) VALUES($1,$2,$3) RETURNING id',[org,user.id,e.enabled?'active':'inactive'])).rows[0];const created=(await c.query<{id:string}>('INSERT INTO directory_principals(organization_id,user_id,external_object_id,account_name,email,display_name,status,managed_fields) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id',[org,user.id,e.externalObjectId,e.accountName?.toLowerCase()??null,e.email?.toLowerCase()??null,e.displayName.trim(),e.enabled?'ACTIVE':'SUSPENDED',JSON.stringify(this.managed(e))])).rows[0];await this.applyRoles(c,created.id,member.id,e.roles??[]);return;}await c.query('UPDATE directory_principals SET account_name=$1,email=$2,display_name=$3,status=$4,managed_fields=$5,updated_at=now() WHERE id=$6',[e.accountName?.toLowerCase()??null,e.email?.toLowerCase()??null,e.displayName.trim(),e.enabled?'ACTIVE':'SUSPENDED',JSON.stringify(this.managed(e)),principal.id]);if(principal.user_id){const member=(await c.query<{id:string}>('UPDATE memberships SET status=$1 WHERE organization_id=$2 AND user_id=$3 RETURNING id',[e.enabled?'active':'inactive',org,principal.user_id])).rows[0];if(member)await this.applyRoles(c,principal.id,member.id,e.roles??[]);}}
  private async applyRoles(c:Db,principal:string,membership:string,assigned:string[]){await c.query('DELETE FROM membership_roles mr USING directory_principal_role_grants g WHERE g.directory_principal_id=$1 AND g.membership_id=mr.membership_id AND g.role_id=mr.role_id',[principal]);await c.query('DELETE FROM directory_principal_role_grants WHERE directory_principal_id=$1',[principal]);for(const code of [...new Set(assigned)].filter(role=>roles.has(role))){const role=(await c.query<{id:string}>('SELECT id FROM roles WHERE code=$1',[code])).rows[0];if(role){await c.query('INSERT INTO membership_roles(membership_id,role_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[membership,role.id]);await c.query('INSERT INTO directory_principal_role_grants(directory_principal_id,membership_id,role_id) VALUES($1,$2,$3)',[principal,membership,role.id]);}}}
}
