import { afterAll, beforeAll, describe, expect, it, vi } from 'vitest';
import { AiGatewayService } from '../src/ai/ai-gateway.service.js';
import { DatabaseService } from '../src/database/database.service.js';
import { TicketService } from '../src/tickets/ticket.service.js';
import { AiCredentialService } from '../src/ai/ai-credential.service.js';

process.env.AI_CREDENTIAL_ENCRYPTION_KEY=Buffer.alloc(32,9).toString('base64');
const database=new DatabaseService(); const credentialService=new AiCredentialService(); const metering={reserveSmartAction:vi.fn(async()=>({id:'reserved'})),settleSmartAction:vi.fn(async()=>({id:'settled'})),releaseSmartAction:vi.fn(async()=>({released:true}))}; const gateway=new AiGatewayService(database,credentialService,metering as never); const tickets=new TicketService(database);
let org=''; let user=''; let ticket=''; const actor=()=>({userId:user,organizationId:org,roles:['REQUESTER']});
beforeAll(async()=>{ const o=await database.query<{id:string}>('INSERT INTO organizations(slug,name) VALUES(\'goal9-test\',\'Goal 9 Test\') ON CONFLICT(slug) DO UPDATE SET name=EXCLUDED.name RETURNING id'); org=o.rows[0].id; const u=await database.query<{id:string}>('INSERT INTO users(email,display_name,password_hash) VALUES(\'goal9@jupiter.local\',\'Goal 9\',\'scrypt$AA$AA\') ON CONFLICT(email) DO UPDATE SET display_name=EXCLUDED.display_name RETURNING id'); user=u.rows[0].id; await database.query('INSERT INTO memberships(organization_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[org,user]); const d=await tickets.createDraft(actor(),{title:'Manual fallback',description:'contact test@example.com'}); ticket=d.id; const encrypted=credentialService.encrypt('test-provider-key'); await database.query(`INSERT INTO organization_ai_settings(organization_id,enabled,model,analysis_model,provider_base_url,api_key_ciphertext,api_key_iv,api_key_auth_tag) VALUES($1,true,'test','test','https://api.openai.com/v1',$2,$3,$4) ON CONFLICT(organization_id) DO UPDATE SET enabled=true,analysis_model='test',api_key_ciphertext=$2,api_key_iv=$3,api_key_auth_tag=$4`,[org,encrypted.ciphertext,encrypted.iv,encrypted.authTag]); });
afterAll(async()=>{ for(const table of ['ai_results','ai_requests','outbox_events','organization_ai_settings','audit_logs','ticket_activities','tickets','memberships']) await database.query(`DELETE FROM ${table} WHERE organization_id=$1`,[org]); await database.query('DELETE FROM organizations WHERE id=$1',[org]); await database.query('DELETE FROM users WHERE id=$1',[user]); await database.onModuleDestroy(); });
describe('AI gateway integration',()=>it('records success and failure without blocking manual tickets',async()=>{ const good=await gateway.enqueue(actor(),ticket,'contact test@example.com'); await gateway.process(good.id,{analyze:async(input)=>{expect(input.configuration.apiKey).toBe('test-provider-key');return {output:{title:'Reviewed title',normalizedDescription:'Reviewed manually',priority:'HIGH',confidence:.9,initialResponse:'AI response'},usage:{inputTokens:2}}}}); const review=await gateway.review(actor(),good.id); expect(review.status).toBe('SUCCEEDED'); expect(review.redacted_input.text).toContain('[email redacted]'); expect(metering.settleSmartAction).toHaveBeenCalledWith(org,good.id,good.id); await gateway.confirm(actor(),good.id); const changed=await database.withOrganization(org,c=>c.query<{title:string}>('SELECT title FROM tickets WHERE id=$1',[ticket])); expect(changed.rows[0].title).toBe('Reviewed title'); const bad=await gateway.enqueue(actor(),ticket,'manual fallback'); await gateway.process(bad.id,{analyze:async()=>{throw new Error('offline')}}); expect((await gateway.review(actor(),bad.id)).status).toBe('FAILED'); expect(metering.releaseSmartAction).toHaveBeenCalledWith(org,bad.id); const audit=await database.withOrganization(org,c=>c.query<{count:number}>("SELECT count(*)::int AS count FROM audit_logs WHERE action IN ('ai.requested','ai.completed','ai.confirmed','ai.failed')")); expect(audit.rows[0].count).toBeGreaterThanOrEqual(4); await expect(gateway.enqueue({...actor(),userId:'another-user'},ticket,'no access')).rejects.toBeDefined(); }));
