import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { DatabaseService } from '../database/database.service.js';

const scopes=new Set(['ROUTED_ONLY','SELECTED_SCOPE','FULL_SUPPORT']);
const policies=new Set(['DISABLED','USER_REQUEST_ALLOWED','ADMIN_APPROVAL_REQUIRED','AUTO_OVERFLOW','ALWAYS_ROUTE']);
@Injectable()
export class AssistService {
  constructor(private readonly database:DatabaseService) {}
  private async platform(userId:string) { const row=(await this.database.query<{is_platform_admin:boolean}>('SELECT is_platform_admin FROM users WHERE id=$1 AND is_active=true',[userId])).rows[0]; if(!row?.is_platform_admin) throw new ForbiddenException(); }
  async agents(userId:string) { await this.platform(userId); return (await this.database.query('SELECT a.user_id,u.display_name,u.email,a.status,a.enabled_at FROM jupiter_support_agents a JOIN users u ON u.id=a.user_id ORDER BY u.display_name')).rows; }
  async saveAgent(actorId:string,input:{userId?:string;status?:'ACTIVE'|'SUSPENDED'}) { await this.platform(actorId); if(!input.userId || !['ACTIVE','SUSPENDED'].includes(input.status??'')) throw new BadRequestException('اطلاعات کارشناس Jupiter معتبر نیست.'); const user=(await this.database.query<{id:string}>('SELECT id FROM users WHERE id=$1 AND is_active=true',[input.userId])).rows[0]; if(!user) throw new NotFoundException('کاربر یافت نشد.'); return this.database.transaction(async client=>{const record=(await client.query<{user_id:string}>('INSERT INTO jupiter_support_agents(user_id,status,enabled_by_user_id) VALUES($1,$2,$3) ON CONFLICT(user_id) DO UPDATE SET status=EXCLUDED.status,enabled_by_user_id=EXCLUDED.enabled_by_user_id,updated_at=now() RETURNING user_id',[user.id,input.status,actorId])).rows[0];await client.query('INSERT INTO audit_logs(organization_id,actor_user_id,action,target_type,target_id,metadata) VALUES(NULL,$1,$2,$3,$4,$5)',[actorId,'assist.agent_saved','jupiter_support_agent',record.user_id,{status:input.status}]);return record;}); }
  async policies(userId:string) { await this.platform(userId); return (await this.database.query('SELECT p.organization_id,o.name AS organization_name,p.request_policy,p.default_access_scope,p.capacity_units,p.assist_sla_minutes,p.updated_at FROM organization_assist_policies p JOIN organizations o ON o.id=p.organization_id ORDER BY o.name')).rows; }
  async savePolicy(actorId:string,input:{organizationId?:string;requestPolicy?:string;defaultAccessScope?:string;capacityUnits?:number;assistSlaMinutes?:number}) { await this.platform(actorId); const sla=input.assistSlaMinutes??480;if(!input.organizationId || !policies.has(input.requestPolicy??'') || !scopes.has(input.defaultAccessScope??'') || !Number.isInteger(input.capacityUnits) || (input.capacityUnits??-1)<0 || !Number.isInteger(sla) || sla<15 || sla>43200) throw new BadRequestException('سیاست Assist معتبر نیست.'); return this.database.withOrganization(input.organizationId,async client=>{const org=(await client.query<{id:string}>('SELECT id FROM organizations WHERE id=$1',[input.organizationId])).rows[0];if(!org)throw new NotFoundException('سازمان یافت نشد.');const record=(await client.query<{organization_id:string}>('INSERT INTO organization_assist_policies(organization_id,request_policy,default_access_scope,capacity_units,assist_sla_minutes,updated_by_user_id) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(organization_id) DO UPDATE SET request_policy=EXCLUDED.request_policy,default_access_scope=EXCLUDED.default_access_scope,capacity_units=EXCLUDED.capacity_units,assist_sla_minutes=EXCLUDED.assist_sla_minutes,updated_by_user_id=EXCLUDED.updated_by_user_id,updated_at=now() RETURNING organization_id',[org.id,input.requestPolicy,input.defaultAccessScope,input.capacityUnits,sla,actorId])).rows[0];await client.query('INSERT INTO audit_logs(organization_id,actor_user_id,action,target_type,target_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[org.id,actorId,'assist.policy_saved','organization_assist_policy',record.organization_id,{requestPolicy:input.requestPolicy,defaultAccessScope:input.defaultAccessScope,capacityUnits:input.capacityUnits,assistSlaMinutes:sla}]);return record;}); }
  async grants(userId:string) { await this.platform(userId); return (await this.database.query('SELECT g.id,g.organization_id,o.name AS organization_name,g.support_agent_user_id,u.display_name AS support_agent_name,g.scope,g.ticket_id,g.department_id,g.category_id,g.allows_restricted,g.starts_at,g.expires_at,g.revoked_at FROM support_access_grants g JOIN organizations o ON o.id=g.organization_id JOIN users u ON u.id=g.support_agent_user_id ORDER BY g.created_at DESC')).rows; }
  async createGrant(actorId:string,input:{organizationId?:string;supportAgentUserId?:string;scope?:string;ticketId?:string;departmentId?:string;categoryId?:string;allowsRestricted?:boolean;expiresAt?:string}) { await this.platform(actorId); const scope=input.scope??'';const expiresAt=input.expiresAt?new Date(input.expiresAt):null;if(!input.organizationId||!input.supportAgentUserId||!scopes.has(scope)||!expiresAt||Number.isNaN(+expiresAt)||expiresAt<=new Date())throw new BadRequestException('اطلاعات مجوز دسترسی معتبر نیست.');const routed=scope==='ROUTED_ONLY'&&Boolean(input.ticketId)&&!input.departmentId&&!input.categoryId;const selected=scope==='SELECTED_SCOPE'&&!input.ticketId&&Boolean(input.departmentId||input.categoryId);const full=scope==='FULL_SUPPORT'&&!input.ticketId&&!input.departmentId&&!input.categoryId;if(!(routed||selected||full)||Boolean(input.allowsRestricted)&&!routed)throw new BadRequestException('دامنهٔ مجوز دسترسی معتبر نیست.');return this.database.withOrganization(input.organizationId,async client=>{const agent=(await client.query<{user_id:string}>('SELECT user_id FROM jupiter_support_agents WHERE user_id=$1 AND status=\'ACTIVE\'',[input.supportAgentUserId])).rows[0];if(!agent)throw new BadRequestException('کارشناس فعال Jupiter یافت نشد.');if(input.ticketId&&!((await client.query('SELECT 1 FROM tickets WHERE id=$1',[input.ticketId])).rowCount))throw new NotFoundException('تیکت یافت نشد.');if(input.departmentId&&!((await client.query('SELECT 1 FROM departments WHERE id=$1',[input.departmentId])).rowCount))throw new NotFoundException('دپارتمان یافت نشد.');if(input.categoryId&&!((await client.query('SELECT 1 FROM categories WHERE id=$1',[input.categoryId])).rowCount))throw new NotFoundException('دسته‌بندی یافت نشد.');const record=(await client.query<{id:string}>('INSERT INTO support_access_grants(organization_id,support_agent_user_id,scope,ticket_id,department_id,category_id,allows_restricted,expires_at,created_by_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id',[input.organizationId,agent.user_id,scope,input.ticketId??null,input.departmentId??null,input.categoryId??null,Boolean(input.allowsRestricted),expiresAt,actorId])).rows[0];await client.query('INSERT INTO audit_logs(organization_id,actor_user_id,action,target_type,target_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[input.organizationId,actorId,'assist.grant_created','support_access_grant',record.id,{scope,allowsRestricted:Boolean(input.allowsRestricted)}]);return record;}); }
  async revokeGrant(actorId:string,id:string) { await this.platform(actorId);const grant=(await this.database.query<{organization_id:string}>('SELECT organization_id FROM support_access_grants WHERE id=$1',[id])).rows[0];if(!grant)throw new NotFoundException('مجوز دسترسی یافت نشد.');return this.database.withOrganization(grant.organization_id,async client=>{const row=(await client.query<{id:string}>('UPDATE support_access_grants SET revoked_at=COALESCE(revoked_at,now()),revoked_by_user_id=COALESCE(revoked_by_user_id,$2) WHERE id=$1 RETURNING id',[id,actorId])).rows[0];await client.query('INSERT INTO audit_logs(organization_id,actor_user_id,action,target_type,target_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[grant.organization_id,actorId,'assist.grant_revoked','support_access_grant',id,{}]);return {id:row.id};}); }
  private admin(actor:{roles:string[]}) { if(!actor.roles.includes('ORG_ADMIN')) throw new ForbiddenException(); }
  async cases(actor:{userId:string;organizationId:string;roles:string[]}) { return this.database.withOrganization(actor.organizationId,async client=>(await client.query(`SELECT c.id,c.ticket_id,c.status,c.request_note,c.assigned_support_agent_user_id,c.assist_sla_due_at,c.created_at FROM assist_cases c WHERE c.requested_by_user_id=$1 OR $2 ORDER BY c.created_at DESC`,[actor.userId,actor.roles.includes('ORG_ADMIN')])).rows); }
  async request(actor:{userId:string;organizationId:string;roles:string[]},ticketId:string,note?:string) { const message=note?.trim()||null;if(message&&message.length>1000)throw new BadRequestException('توضیح درخواست طولانی است.');return this.database.withOrganization(actor.organizationId,async client=>{const ticket=(await client.query<{id:string}>('SELECT id FROM tickets WHERE id=$1 AND requester_user_id=$2',[ticketId,actor.userId])).rows[0];if(!ticket)throw new NotFoundException('تیکت قابل درخواست نیست.');const policy=(await client.query<{request_policy:string}>('SELECT request_policy FROM organization_assist_policies WHERE organization_id=$1',[actor.organizationId])).rows[0];if(!policy||policy.request_policy==='DISABLED')throw new ForbiddenException('پشتیبانی Jupiter برای سازمان فعال نیست.');const status=policy.request_policy==='ADMIN_APPROVAL_REQUIRED'?'PENDING_APPROVAL':policy.request_policy==='USER_REQUEST_ALLOWED'?'REQUESTED':'QUEUED';const record=(await client.query<{id:string;status:string}>('INSERT INTO assist_cases(organization_id,ticket_id,requested_by_user_id,status,request_note) VALUES($1,$2,$3,$4,$5) ON CONFLICT(organization_id,ticket_id) DO UPDATE SET updated_at=assist_cases.updated_at RETURNING id,status',[actor.organizationId,ticket.id,actor.userId,status,message])).rows[0];await client.query('INSERT INTO audit_logs(organization_id,actor_user_id,action,target_type,target_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[actor.organizationId,actor.userId,'assist.requested','assist_case',record.id,{status:record.status}]);return record;}); }
  async approve(actor:{userId:string;organizationId:string;roles:string[]},id:string) { this.admin(actor);return this.database.withOrganization(actor.organizationId,async client=>{const record=(await client.query<{id:string;status:string}>("UPDATE assist_cases SET status='QUEUED',updated_at=now() WHERE id=$1 AND status IN ('PENDING_APPROVAL','REQUESTED') RETURNING id,status",[id])).rows[0];if(!record)throw new NotFoundException('درخواست قابل تأیید نیست.');await client.query('INSERT INTO audit_logs(organization_id,actor_user_id,action,target_type,target_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[actor.organizationId,actor.userId,'assist.approved','assist_case',id,{}]);return record;}); }
  async platformCases(userId:string) { await this.platform(userId);return (await this.database.query('SELECT c.id,c.organization_id,o.name AS organization_name,c.ticket_id,c.status,c.request_note,c.assigned_support_agent_user_id,c.assist_sla_due_at,c.created_at FROM assist_cases c JOIN organizations o ON o.id=c.organization_id ORDER BY c.created_at DESC')).rows; }
  async accept(agentId:string,id:string) { const raw=(await this.database.query<{organization_id:string;ticket_id:string}>('SELECT organization_id,ticket_id FROM assist_cases WHERE id=$1',[id])).rows[0];if(!raw)throw new NotFoundException('پروندهٔ Assist یافت نشد.');if(!await this.canAccessTicket(agentId,raw.organization_id,raw.ticket_id))throw new ForbiddenException('مجوز دسترسی به این تیکت ندارید.');return this.database.withOrganization(raw.organization_id,async client=>{const policy=(await client.query<{capacity_units:number;assist_sla_minutes:number}>('SELECT capacity_units,assist_sla_minutes FROM organization_assist_policies WHERE organization_id=$1 FOR UPDATE',[raw.organization_id])).rows[0];const commercial=Boolean((await client.query<{allowed:boolean}>("SELECT NOT EXISTS(SELECT 1 FROM commercial_subscriptions) OR EXISTS(SELECT 1 FROM commercial_subscriptions WHERE status IN ('ACTIVE','TRIAL') OR (status='PAST_DUE' AND (grace_ends_at IS NULL OR grace_ends_at>now()))) allowed")).rows[0]?.allowed);if(!commercial)throw new ForbiddenException('پذیرش جدید Assist برای اشتراک فعلی سازمان مجاز نیست.');if(!policy||policy.capacity_units<=0)throw new ForbiddenException('ظرفیت جدید پشتیبانی Jupiter موجود نیست.');const record=(await client.query<{id:string}>('UPDATE assist_cases SET status=\'ACCEPTED\',assigned_support_agent_user_id=$2,accepted_at=now(),assist_sla_due_at=now()+($3::text||\' minutes\')::interval,capacity_settled_at=now(),updated_at=now() WHERE id=$1 AND status=\'QUEUED\' AND capacity_settled_at IS NULL RETURNING id',[id,agentId,policy.assist_sla_minutes])).rows[0];if(!record)throw new NotFoundException('پرونده قابل پذیرش نیست.');await client.query('UPDATE organization_assist_policies SET capacity_units=capacity_units-1,updated_at=now() WHERE organization_id=$1',[raw.organization_id]);await client.query('INSERT INTO audit_logs(organization_id,actor_user_id,action,target_type,target_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[raw.organization_id,agentId,'assist.accepted','assist_case',id,{capacitySettled:true}]);return record;}); }
  async agentState(agentId:string,id:string,status?:string) { const allowed=new Set(['IN_PROGRESS','WAITING_FOR_ORGANIZATION','COMPLETED','DECLINED']);if(!status||!allowed.has(status))throw new BadRequestException('وضعیت Assist معتبر نیست.');const raw=(await this.database.query<{organization_id:string;ticket_id:string}>('SELECT organization_id,ticket_id FROM assist_cases WHERE id=$1',[id])).rows[0];if(!raw||!await this.canAccessTicket(agentId,raw.organization_id,raw.ticket_id))throw new ForbiddenException();return this.database.withOrganization(raw.organization_id,async client=>{const from=status==='DECLINED'?['QUEUED']:['ACCEPTED','IN_PROGRESS','WAITING_FOR_ORGANIZATION'];const record=(await client.query<{id:string}>(`UPDATE assist_cases SET status=$2,completed_at=CASE WHEN $2='COMPLETED' THEN now() ELSE completed_at END,updated_at=now() WHERE id=$1 AND status=ANY($3::text[]) RETURNING id`,[id,status,from])).rows[0];if(!record)throw new NotFoundException('تغییر وضعیت مجاز نیست.');await client.query('INSERT INTO audit_logs(organization_id,actor_user_id,action,target_type,target_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[raw.organization_id,agentId,'assist.state_changed','assist_case',id,{status}]);return record;}); }
  async requestAdditionalAccess(agentId:string,id:string,durationCode?:string) { const durations=new Set(['TWO_HOURS','TWENTY_FOUR_HOURS','UNTIL_CASE_COMPLETION']);if(!durationCode||!durations.has(durationCode))throw new BadRequestException('مدت دسترسی معتبر نیست.');const raw=(await this.database.query<{organization_id:string;ticket_id:string}>('SELECT organization_id,ticket_id FROM assist_cases WHERE id=$1',[id])).rows[0];if(!raw||!await this.canAccessTicket(agentId,raw.organization_id,raw.ticket_id))throw new ForbiddenException();return this.database.withOrganization(raw.organization_id,async client=>{const row=(await client.query<{id:string}>('INSERT INTO assist_access_requests(organization_id,assist_case_id,support_agent_user_id,duration_code) VALUES($1,$2,$3,$4) RETURNING id',[raw.organization_id,id,agentId,durationCode])).rows[0];await client.query('INSERT INTO audit_logs(organization_id,actor_user_id,action,target_type,target_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[raw.organization_id,agentId,'assist.additional_access_requested','assist_access_request',row.id,{durationCode}]);return row;}); }
  async approveAdditionalAccess(adminId:string,id:string) { await this.platform(adminId);const raw=(await this.database.query<{organization_id:string;assist_case_id:string;support_agent_user_id:string;duration_code:string}>('SELECT organization_id,assist_case_id,support_agent_user_id,duration_code FROM assist_access_requests WHERE id=$1 AND status=\'REQUESTED\'',[id])).rows[0];if(!raw)throw new NotFoundException('درخواست دسترسی یافت نشد.');return this.database.withOrganization(raw.organization_id,async client=>{const ticket=(await client.query<{ticket_id:string;is_restricted:boolean}>('SELECT ticket_id,(SELECT is_restricted FROM tickets WHERE id=assist_cases.ticket_id) AS is_restricted FROM assist_cases WHERE id=$1',[raw.assist_case_id])).rows[0];const expiry=raw.duration_code==='TWO_HOURS'?new Date(Date.now()+7_200_000):raw.duration_code==='TWENTY_FOUR_HOURS'?new Date(Date.now()+86_400_000):new Date(Date.now()+30*86_400_000);const grant=(await client.query<{id:string}>('INSERT INTO support_access_grants(organization_id,support_agent_user_id,scope,ticket_id,allows_restricted,expires_at,created_by_user_id) VALUES($1,$2,\'ROUTED_ONLY\',$3,$4,$5,$6) RETURNING id',[raw.organization_id,raw.support_agent_user_id,ticket.ticket_id,ticket.is_restricted,expiry,adminId])).rows[0];await client.query("UPDATE assist_access_requests SET status='APPROVED',reviewed_by_user_id=$2,reviewed_at=now() WHERE id=$1",[id,adminId]);return grant;}); }
  async canAccessTicket(supportAgentUserId:string,organizationId:string,ticketId:string) {
    return this.database.withOrganization(organizationId, async client => {
      const ticket = (await client.query<{is_restricted:boolean;department_id:string|null;category_id:string|null}>(
        'SELECT is_restricted,department_id,category_id FROM tickets WHERE id=$1', [ticketId],
      )).rows[0];
      if (!ticket) return false;
      const isRestricted = ticket.is_restricted;
      const departmentId = ticket.department_id;
      const categoryId = ticket.category_id;
      const agent = ((await client.query("SELECT 1 FROM jupiter_support_agents WHERE user_id=$1 AND status='ACTIVE'", [supportAgentUserId])).rowCount ?? 0) > 0;
      if (!agent) return false;
      const grant = await client.query(`SELECT 1 FROM support_access_grants
        WHERE support_agent_user_id=$1 AND revoked_at IS NULL AND starts_at<=now() AND expires_at>now()
          AND (CASE WHEN $2 THEN ticket_id=$3 AND allows_restricted
                    ELSE ticket_id=$3 OR scope='FULL_SUPPORT' OR (scope='SELECTED_SCOPE' AND (department_id=$4 OR category_id=$5)) END)
        LIMIT 1`, [supportAgentUserId,isRestricted,ticketId,departmentId,categoryId]);
      return (grant.rowCount ?? 0) > 0;
    });
  }
}
