import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { PoolClient } from 'pg';
import { DatabaseService } from '../database/database.service.js';
import { NotificationService } from '../notifications/notification.service.js';

type Source='INCLUDED'|'PROMOTIONAL'|'MANUAL'|'LEGACY_MIGRATED'|'PURCHASED';
const sources=new Set<Source>(['INCLUDED','PROMOTIONAL','MANUAL','LEGACY_MIGRATED','PURCHASED']);
// Membership state intentionally remains lower-case; it is the canonical value
// constrained by the identity migration (unlike commercial status enums).
const ACTIVE_MEMBERSHIP_STATUS='active';
@Injectable()
export class AssistCapacityService {
  constructor(private readonly database:DatabaseService, private readonly notifications?:NotificationService) {}
  private async notify(organizationId:string,alertCode:string,windowKey:string) { if(!this.notifications)return;const recipients=await this.database.withOrganization(organizationId,async c=>{const mark=(await c.query('INSERT INTO commercial_notification_marks(organization_id,alert_code,capability_code,window_key) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING RETURNING organization_id',[organizationId,alertCode,'JUPITER_ASSIST',windowKey])).rowCount??0;if(!mark)return [];return (await c.query<{user_id:string}>(`SELECT DISTINCT m.user_id FROM memberships m JOIN membership_roles mr ON mr.membership_id=m.id JOIN roles r ON r.id=mr.role_id JOIN users u ON u.id=m.user_id WHERE m.organization_id=$1 AND m.status=$2 AND u.is_active AND r.code='ORG_OWNER'`,[organizationId,ACTIVE_MEMBERSHIP_STATUS])).rows.map(x=>x.user_id);});if(recipients.length)await this.notifications.publish(organizationId,recipients,{type:`assist.capacity.${alertCode.toLowerCase()}`,occurredAt:new Date().toISOString()}); }
  private async platform(userId:string) { const row=(await this.database.query<{is_platform_admin:boolean}>('SELECT is_platform_admin FROM users WHERE id=$1',[userId])).rows[0]; if(!row?.is_platform_admin) throw new ForbiddenException(); }
  private async audit(client:PoolClient,organizationId:string|null,actorId:string,action:string,target:string,id:string,metadata:object) { await client.query('INSERT INTO audit_logs(organization_id,actor_user_id,action,target_type,target_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[organizationId,actorId,action,target,id,metadata]); }
  async packages(actorId:string) { await this.platform(actorId); return (await this.database.query('SELECT p.id,p.code,p.name,p.included_units,p.status,p.created_at,cp.code AS product_code,cp.name AS product_name FROM assist_capacity_packages p JOIN commercial_products cp ON cp.id=p.product_id ORDER BY p.created_at DESC')).rows; }
  async savePackage(actorId:string,input:{productId?:string;code?:string;name?:string;includedUnits?:number;status?:'ACTIVE'|'SUSPENDED'}) { await this.platform(actorId); const code=input.code?.trim().toUpperCase(); const name=input.name?.trim(); if(!input.productId||!code||!name||!Number.isInteger(input.includedUnits)||(input.includedUnits??0)<=0||!['ACTIVE','SUSPENDED'].includes(input.status??'ACTIVE')) throw new BadRequestException('اطلاعات بستهٔ Assist معتبر نیست.'); return this.database.transaction(async client=>{const product=(await client.query<{id:string;code:string}>('SELECT id,code FROM commercial_products WHERE id=$1 AND status=\'ACTIVE\'',[input.productId])).rows[0];if(!product||!product.code.startsWith('ASSIST_'))throw new BadRequestException('محصول Assist فعال معتبر نیست.'); const row=(await client.query('INSERT INTO assist_capacity_packages(product_id,code,name,included_units,status,created_by_user_id) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,code',[product.id,code,name,input.includedUnits,input.status??'ACTIVE',actorId])).rows[0] as {id:string;code:string}; await this.audit(client,null,actorId,'ASSIST_PACKAGE_CREATED','assist_capacity_package',row.id,{code:row.code,productCode:product.code}); return row;}); }
  async setPackageStatus(actorId:string,packageId:string,input:{status?:'ACTIVE'|'SUSPENDED';reason?:string}) { await this.platform(actorId);const status=input.status,reason=input.reason?.trim();if(!['ACTIVE','SUSPENDED'].includes(status??'')||!reason||reason.length<3)throw new BadRequestException('وضعیت بسته و دلیل آن الزامی است.');return this.database.transaction(async client=>{const row=(await client.query<{id:string;status:string}>('UPDATE assist_capacity_packages SET status=$2,updated_at=now() WHERE id=$1 AND status<>$2 RETURNING id,status',[packageId,status])).rows[0];if(!row)throw new NotFoundException('بستهٔ Assist یافت نشد یا وضعیت آن تغییر نکرده است.');await this.audit(client,null,actorId,status==='SUSPENDED'?'ASSIST_PACKAGE_SUSPENDED':'ASSIST_PACKAGE_REACTIVATED','assist_capacity_package',row.id,{reason,scope:'PACKAGE_DEFINITION_ONLY'});return row;}); }
  async allocations(actorId:string,organizationId?:string) { await this.platform(actorId); if(!organizationId) throw new BadRequestException('سازمان هدف الزامی است.'); return this.database.withOrganization(organizationId,async client=>(await client.query(`SELECT a.id,a.source,a.allocated_units,a.status,a.starts_at,a.expires_at,a.contract_reference,p.name AS package_name,p.code AS package_code,COALESCE(SUM(l.unit_delta),0)::int AS remaining FROM organization_assist_capacity_allocations a LEFT JOIN assist_capacity_packages p ON p.id=a.assist_capacity_package_id LEFT JOIN assist_capacity_ledger l ON l.allocation_id=a.id WHERE a.organization_id=$1 GROUP BY a.id,p.name,p.code ORDER BY a.expires_at NULLS LAST,a.created_at,a.id`,[organizationId])).rows); }
  async report(actorId:string) { await this.platform(actorId); return (await this.database.query(`SELECT o.name AS organization_name,cp.code AS product_code,p.name AS package_name,a.source,a.allocated_units,a.status,a.starts_at,a.expires_at,COALESCE(SUM(l.unit_delta),0)::int AS remaining,count(l.id) FILTER (WHERE l.event_type='CONSUMED')::int AS used_cases FROM organization_assist_capacity_allocations a JOIN organizations o ON o.id=a.organization_id LEFT JOIN assist_capacity_packages p ON p.id=a.assist_capacity_package_id LEFT JOIN commercial_products cp ON cp.id=p.product_id LEFT JOIN assist_capacity_ledger l ON l.allocation_id=a.id GROUP BY a.id,o.name,cp.code,p.name ORDER BY o.name,a.expires_at NULLS LAST,a.created_at`)).rows; }
  async assign(actorId:string,input:{organizationId?:string;packageId?:string;source?:Source;units?:number;startsAt?:string;expiresAt?:string;contractReference?:string}) { await this.platform(actorId); const source=input.source??'PURCHASED', start=new Date(input.startsAt??Date.now()), end=input.expiresAt?new Date(input.expiresAt):null, organizationId=input.organizationId, packageId=input.packageId, units=input.units; if(!organizationId||!packageId||!sources.has(source)||!Number.isInteger(units)||(units??0)<=0||Number.isNaN(+start)||!end||Number.isNaN(+end)||end<=start)throw new BadRequestException('تخصیص ظرفیت Assist معتبر نیست.'); const row=await this.database.withOrganization(organizationId,async client=>{const pack=(await client.query<{id:string;status:string}>('SELECT id,status FROM assist_capacity_packages WHERE id=$1',[packageId])).rows[0];if(!pack||pack.status!=='ACTIVE')throw new BadRequestException('بستهٔ Assist فعال یافت نشد.');const r=(await client.query<{id:string}>('INSERT INTO organization_assist_capacity_allocations(organization_id,assist_capacity_package_id,source,allocated_units,starts_at,expires_at,contract_reference,created_by_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id',[organizationId,pack.id,source,units,start,end,input.contractReference?.trim()||null,actorId])).rows[0];await client.query('INSERT INTO assist_capacity_ledger(organization_id,allocation_id,event_type,unit_delta,reason,actor_user_id) VALUES($1,$2,\'ALLOCATED\',$3,\'Package assignment\',$4)',[organizationId,r.id,units,actorId]);await this.audit(client,organizationId,actorId,'ASSIST_PACKAGE_ASSIGNED','organization_assist_capacity_allocation',r.id,{source,units});return r;});await this.notify(organizationId,'ASSIST_PACKAGE_ASSIGNED',row.id);return row; }
  async adjust(actorId:string,input:{organizationId?:string;allocationId?:string;units?:number;reason?:string}) { await this.platform(actorId);const reason=input.reason?.trim(), organizationId=input.organizationId, allocationId=input.allocationId, units=input.units;if(!organizationId||!allocationId||!Number.isInteger(units)||!units||!reason||reason.length<3)throw new BadRequestException('اصلاح ظرفیت و دلیل آن الزامی است.');return this.database.withOrganization(organizationId,async client=>{const a=(await client.query<{id:string;remaining:number}>('SELECT a.id,COALESCE(SUM(l.unit_delta),0)::int remaining FROM organization_assist_capacity_allocations a LEFT JOIN assist_capacity_ledger l ON l.allocation_id=a.id WHERE a.id=$1 AND a.organization_id=$2 GROUP BY a.id FOR UPDATE',[allocationId,organizationId])).rows[0];if(!a)throw new NotFoundException('تخصیص ظرفیت یافت نشد.');if(a.remaining+units<0)throw new BadRequestException('ظرفیت باقیمانده نمی‌تواند منفی شود.');const row=(await client.query<{id:string}>('INSERT INTO assist_capacity_ledger(organization_id,allocation_id,event_type,unit_delta,reason,actor_user_id) VALUES($1,$2,\'ADJUSTED\',$3,$4,$5) RETURNING id',[organizationId,a.id,units,reason,actorId])).rows[0];await this.audit(client,organizationId,actorId,'ASSIST_CAPACITY_ADJUSTED','assist_capacity_ledger',row.id,{units,reason});return row;}); }
  async suspend(actorId:string,input:{organizationId?:string;allocationId?:string;reason?:string}) { await this.platform(actorId);const organizationId=input.organizationId, allocationId=input.allocationId, reason=input.reason?.trim();if(!organizationId||!allocationId||!reason)throw new BadRequestException('سازمان، تخصیص و دلیل الزامی است.');return this.database.withOrganization(organizationId,async client=>{const row=(await client.query<{id:string}>('UPDATE organization_assist_capacity_allocations SET status=\'SUSPENDED\',updated_at=now() WHERE id=$1 AND organization_id=$2 AND status=\'ACTIVE\' RETURNING id',[allocationId,organizationId])).rows[0];if(!row)throw new NotFoundException('تخصیص فعال یافت نشد.');await this.audit(client,organizationId,actorId,'ASSIST_PACKAGE_SUSPENDED','organization_assist_capacity_allocation',row.id,{reason});return row;}); }
  async ownerSummary(actor:{userId:string;organizationId:string;roles:string[]}) { if(!actor.roles.includes('ORG_OWNER'))throw new ForbiddenException(); return this.database.withOrganization(actor.organizationId,async client=>{const allocations=(await client.query(`SELECT a.source,a.allocated_units,a.status,a.starts_at,a.expires_at,p.name AS package_name,p.code AS package_code,COALESCE(SUM(l.unit_delta),0)::int remaining FROM organization_assist_capacity_allocations a LEFT JOIN assist_capacity_packages p ON p.id=a.assist_capacity_package_id LEFT JOIN assist_capacity_ledger l ON l.allocation_id=a.id WHERE a.organization_id=$1 GROUP BY a.id,p.name,p.code ORDER BY a.expires_at NULLS LAST,a.created_at,a.id`,[actor.organizationId])).rows; const cases=(await client.query("SELECT count(*) FILTER (WHERE status='ACCEPTED')::int AS accepted, count(*) FILTER (WHERE status IN ('ACCEPTED','IN_PROGRESS','WAITING_FOR_ORGANIZATION'))::int AS in_progress FROM assist_cases WHERE organization_id=$1",[actor.organizationId])).rows[0];return {allocations,cases};}); }
  async consumeInTransaction(client:PoolClient,organizationId:string,caseId:string,actorId:string) { await client.query('SELECT pg_advisory_xact_lock(hashtext($1))',[`assist-capacity:${organizationId}`]); const existing=(await client.query<{id:string}>('SELECT id FROM assist_capacity_ledger WHERE organization_id=$1 AND assist_case_id=$2 AND event_type=\'CONSUMED\'',[organizationId,caseId])).rows[0];if(existing)return existing; const allocation=(await client.query<{id:string}>(`SELECT a.id FROM organization_assist_capacity_allocations a LEFT JOIN assist_capacity_ledger l ON l.allocation_id=a.id WHERE a.organization_id=$1 AND a.status='ACTIVE' AND a.starts_at<=now() AND (a.expires_at IS NULL OR a.expires_at>now()) GROUP BY a.id,a.source,a.expires_at,a.created_at HAVING COALESCE(SUM(l.unit_delta),0)>0 ORDER BY CASE a.source WHEN 'INCLUDED' THEN 1 WHEN 'PROMOTIONAL' THEN 2 WHEN 'MANUAL' THEN 2 WHEN 'LEGACY_MIGRATED' THEN 2 WHEN 'PURCHASED' THEN 3 END,a.expires_at NULLS LAST,a.created_at,a.id LIMIT 1`,[organizationId])).rows[0];if(!allocation)throw new ForbiddenException('ظرفیت جدید پشتیبانی Jupiter موجود نیست.');const ledger=(await client.query<{id:string}>('INSERT INTO assist_capacity_ledger(organization_id,allocation_id,assist_case_id,event_type,unit_delta,reason,actor_user_id) VALUES($1,$2,$3,\'CONSUMED\',-1,\'Assist case accepted\',$4) RETURNING id',[organizationId,allocation.id,caseId,actorId])).rows[0];await this.audit(client,organizationId,actorId,'ASSIST_CAPACITY_CONSUMED','assist_capacity_ledger',ledger.id,{assistCaseId:caseId});return ledger; }
}
